services:
  # --- База данных Auth---
  db:
    image: postgres:15-alpine
    container_name: rewind-db
    environment:
      POSTGRES_USER: rewind_user
      POSTGRES_PASSWORD: rewind_password
      POSTGRES_DB: rewind_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rewind_user -d rewind_db" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - db_data:/var/lib/postgresql/data

    # --- База данных Group---
  group-db:
    image: postgres:15-alpine
    container_name: rewind-group-db
    environment:
      POSTGRES_USER: rewind_user
      POSTGRES_PASSWORD: rewind_password
      POSTGRES_DB: rewind_db
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rewind_user -d rewind_db" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - db_group_data:/var/lib/postgresql/data

  # --- Сервисы Go ---

  api-gateway-service:
    build: ./api-gateway-service # Путь к Dockerfile для api-gateway-service
    container_name: rewind-api-gateway-service
    environment:
      API_GATEWAY_PORT: "8080"
      AUTH_SERVICE_GRPC_ADDRESS: rewind-auth-service:50051
      GROUP_SERVICE_GRPC_ADDRESS: rewind-group-service:50052
      # MEMORY_SERVICE_GRPC_ADDRESS: rewind-memory-service:50053
      # NOTIFICATION_SERVICE_GRPC_ADDRESS: rewind-notification-service:50054
    ports:
      - "8080:8080" # Или другой порт по вашему выбору для доступа к API Gateway
    depends_on:
      auth-service:
        condition: service_started
      # Добавьте зависимости от других сервисов по мере необходимости
      # rewind-group-service:
      #   condition: service_started
      # rewind-memory-service:
      #   condition: service_started
      # rewind-notification-service:
      #   condition: service_started


  auth-service:
    build: ./auth-service # Обновленный путь к Dockerfile
    container_name: rewind-auth-service
    ports:
      - "50051:50051"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started

  group-service:
    build: ./group-service # Обновленный путь к Dockerfile
    container_name: rewind-group-service
    ports:
      - "50052:50052"
    depends_on:
      group-db:
        condition: service_healthy
      auth-service:
        condition: service_started
#
#  memory-service:
#    build: ./memory-service # Обновленный путь к Dockerfile
#    container_name: rewind-memory-service
#    environment:
#      DATABASE_URL: postgres://rewind_user:rewind_password@db:5432/rewind_db?sslmode=disable
#      GRPC_PORT: 50054
#      AUTH_SERVICE_GRPC_ADDRESS: auth-service:50051
#      GROUP_SERVICE_GRPC_ADDRESS: group-service:50052
#      NOTIFICATION_SERVICE_GRPC_ADDRESS: notification-service:50053
#      STORAGE_BUCKET_NAME: your-s3-bucket-name
#      STORAGE_REGION: your-s3-region
#      STORAGE_ACCESS_KEY_ID: your-s3-access-key-id
#      STORAGE_SECRET_ACCESS_KEY: your-s3-secret-access-key
#      STORAGE_ENDPOINT: your-s3-endpoint
#    ports:
#      - "50054:50054"
#    depends_on:
#      - db
#      - auth-service
#      - group-service
#      - notification-service

  notification-service:
    build: ./notification-service # Обновленный путь к Dockerfile
    container_name: rewind-notification-service
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
      GRPC_PORT: 50053
    ports:
      - "50053:50053"
    depends_on:
      rabbitmq:
        condition: service_healthy

  # --- API Gateway (Nginx) ---
  nginx:
    image: nginx:stable-alpine
    container_name: rewind-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Монтируем наш файл конфигурации сайта внутрь контейнера Nginx
      # Он будет прочитан Nginx'ом
      - ./nginx/conf/rewindapp.ru.conf:/etc/nginx/conf.d/rewindapp.ru.conf:ro
      # Монтируем тома для хранения сертификатов Let's Encrypt и файлов конфигурации Certbot
      # Nginx будет читать сертификаты из этих томов
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      # Монтируем том для прохождения проверки домена Certbot'ом (Webroot)
      # Nginx должен отдавать файлы из этой директории по адресу /.well-known/acme-challenge/
      - www-data:/var/www/certbot
      - ./nginx/certs:/etc/nginx/certs:ro


    depends_on:
      # Nginx зависит от сервиса приложения, который он проксирует
      - api-gateway-service


  # --- Certbot ---
  # Этот сервис используется для получения и продления сертификатов
  # Он не работает постоянно, а запускается по мере необходимости
  certbot:
    image: certbot/certbot # Используем официальный образ Certbot
    container_name: rewind-certbot
    volumes:
      # Монтируем те же тома, что и Nginx, чтобы certbot мог писать сертификаты и читать настройки
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      # Монтируем тот же том для прохождения проверки домена (Certbot будет писать сюда файлы)
      - www-data:/var/www/certbot
      # Опционально: можно смонтировать конфиги Nginx, если Certbot используется с плагином --nginx
      # но метод --webroot проще в Docker. Если используете --webroot, этот том не нужен:
      # - ./nginx/conf:/etc/nginx/conf.d:ro

    depends_on:
      # Certbot должен быть запущен, когда Nginx готов принимать запросы для проверки домена по 80 порту
      - nginx

    # Команда Certbot запускается вручную или через скрипт/cron
    # Сам контейнер не должен быть запущен в обычном compose up -d

  # --- Очередь сообщений ---
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rewind-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "status" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: rewind-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # --- Мониторинг (Prometheus & Grafana) ---
#  prometheus:
#    image: prom/prometheus:v2.48.1
#    container_name: rewind-prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./Rewind/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro # Обновленный путь к prometheus.yml
#      - prometheus_data:/prometheus
#    depends_on:
#      - auth-service
#
#  grafana:
#    image: grafana/grafana:10.2.3
#    container_name: rewind-grafana
#    ports:
#      - "3000:3000"
#    environment:
#      GF_SECURITY_ADMIN_USER: admin
#      GF_SECURITY_ADMIN_PASSWORD: admin
#    volumes:
#      - grafana_data:/var/lib/grafana
#    depends_on:
#      - prometheus

volumes:
  db_data:
  db_group_data:
  rabbitmq_data:
  redis_data:
  certbot-etc:
  certbot-var:
  www-data:
#  prometheus_data:
#  grafana_data:
