// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/clients/media.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_UNSPECIFIED MediaType = 0
	MediaType_image       MediaType = 1
	MediaType_video       MediaType = 2
	MediaType_quote       MediaType = 3
	MediaType_avatar      MediaType = 4
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "image",
		2: "video",
		3: "quote",
		4: "avatar",
	}
	MediaType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"image":       1,
		"video":       2,
		"quote":       3,
		"avatar":      4,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_clients_media_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_proto_clients_media_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_proto_clients_media_proto_rawDescGZIP(), []int{0}
}

type UploadMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`                          // The binary data of the file
	MediaType     MediaType              `protobuf:"varint,2,opt,name=media_type,json=mediaType,proto3,enum=media.MediaType" json:"media_type,omitempty"` // The type of media (e.g., "image", "video")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaRequest) Reset() {
	*x = UploadMediaRequest{}
	mi := &file_proto_clients_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaRequest) ProtoMessage() {}

func (x *UploadMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaRequest.ProtoReflect.Descriptor instead.
func (*UploadMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_media_proto_rawDescGZIP(), []int{0}
}

func (x *UploadMediaRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadMediaRequest) GetMediaType() MediaType {
	if x != nil {
		return x.MediaType
	}
	return MediaType_UNSPECIFIED
}

type UploadMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"` // The URL of the uploaded file in S3
	FileKey       string                 `protobuf:"bytes,2,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"` // The key used to store the file in S3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaResponse) Reset() {
	*x = UploadMediaResponse{}
	mi := &file_proto_clients_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaResponse) ProtoMessage() {}

func (x *UploadMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaResponse.ProtoReflect.Descriptor instead.
func (*UploadMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMediaResponse) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *UploadMediaResponse) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

var File_proto_clients_media_proto protoreflect.FileDescriptor

const file_proto_clients_media_proto_rawDesc = "" +
	"\n" +
	"\x19proto/clients/media.proto\x12\x05media\"b\n" +
	"\x12UploadMediaRequest\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12/\n" +
	"\n" +
	"media_type\x18\x02 \x01(\x0e2\x10.media.MediaTypeR\tmediaType\"K\n" +
	"\x13UploadMediaResponse\x12\x19\n" +
	"\bfile_url\x18\x01 \x01(\tR\afileUrl\x12\x19\n" +
	"\bfile_key\x18\x02 \x01(\tR\afileKey*I\n" +
	"\tMediaType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\t\n" +
	"\x05image\x10\x01\x12\t\n" +
	"\x05video\x10\x02\x12\t\n" +
	"\x05quote\x10\x03\x12\n" +
	"\n" +
	"\x06avatar\x10\x042T\n" +
	"\fMediaService\x12D\n" +
	"\vUploadMedia\x12\x19.media.UploadMediaRequest\x1a\x1a.media.UploadMediaResponseB(Z&Rewind-2.0/Backend/media-service/protob\x06proto3"

var (
	file_proto_clients_media_proto_rawDescOnce sync.Once
	file_proto_clients_media_proto_rawDescData []byte
)

func file_proto_clients_media_proto_rawDescGZIP() []byte {
	file_proto_clients_media_proto_rawDescOnce.Do(func() {
		file_proto_clients_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_clients_media_proto_rawDesc), len(file_proto_clients_media_proto_rawDesc)))
	})
	return file_proto_clients_media_proto_rawDescData
}

var file_proto_clients_media_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_clients_media_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_clients_media_proto_goTypes = []any{
	(MediaType)(0),              // 0: media.MediaType
	(*UploadMediaRequest)(nil),  // 1: media.UploadMediaRequest
	(*UploadMediaResponse)(nil), // 2: media.UploadMediaResponse
}
var file_proto_clients_media_proto_depIdxs = []int32{
	0, // 0: media.UploadMediaRequest.media_type:type_name -> media.MediaType
	1, // 1: media.MediaService.UploadMedia:input_type -> media.UploadMediaRequest
	2, // 2: media.MediaService.UploadMedia:output_type -> media.UploadMediaResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_clients_media_proto_init() }
func file_proto_clients_media_proto_init() {
	if File_proto_clients_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_clients_media_proto_rawDesc), len(file_proto_clients_media_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_clients_media_proto_goTypes,
		DependencyIndexes: file_proto_clients_media_proto_depIdxs,
		EnumInfos:         file_proto_clients_media_proto_enumTypes,
		MessageInfos:      file_proto_clients_media_proto_msgTypes,
	}.Build()
	File_proto_clients_media_proto = out.File
	file_proto_clients_media_proto_goTypes = nil
	file_proto_clients_media_proto_depIdxs = nil
}
