syntax = "proto3";

package auth;

option go_package = "Rewind-2.0/Backend/auth_service/proto";

service AuthService {
  rpc StartRegistration(StartRegistrationRequest) returns (StartRegistrationResponse) {}
  rpc VerifyEmailCode(VerifyEmailCodeRequest) returns (VerifyEmailCodeResponse) {}
  rpc SetPasswordAndUsername(SetPasswordAndUsernameRequest) returns (SetPasswordAndUsernameResponse) {}
  rpc Login(LoginRequest) returns (LoginResponse) {}
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse) {}
  rpc ForgotPassword(ForgotPasswordRequest) returns (ForgotPasswordResponse) {}
  rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse) {}
  rpc Logout(LogoutRequest) returns (LogoutResponse) {}
  // TODO delete in future
  rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse) {}
  rpc GetUsersByIDs(GetUsersByIDsRequest) returns (GetUsersByIDsResponse) {}
}

message User {
  uint64 id = 1;
  string username = 2;
  string email = 3;
  string image = 4;
}

message StartRegistrationRequest {
  string email = 1;
}

message StartRegistrationResponse {
  string registration_id = 1; // Unique ID to track the registration process
  bool success = 2;
}

message VerifyEmailCodeRequest {
  string registration_id = 1;
  string verification_code = 2;
}

message VerifyEmailCodeResponse {
  bool success = 1;
}

message SetPasswordAndUsernameRequest {
  string registration_id = 1;
  string password = 2;
  string username = 3;
}

message SetPasswordAndUsernameResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message RefreshTokenRequest {
  string refresh_token = 1;
}

message RefreshTokenResponse {
  string access_token = 1;
}

message ForgotPasswordRequest {
  string email = 1;
}

message ForgotPasswordResponse {
  bool success = 1;
}

message ResetPasswordRequest {
  string token = 1;
  string new_password = 2;
}

message ResetPasswordResponse {
  bool success = 1;
}

message LogoutRequest {
  string refresh_token = 1;
}

message LogoutResponse {
  bool success = 1;
}

message DeleteUserRequest {
  string email = 1;
}

message DeleteUserResponse {
  bool success = 1;
}

// Запрос для получения информации о пользователях по списку их ID
message GetUsersByIDsRequest {
  repeated uint64 user_ids = 1; // Список ID пользователей, информацию о которых нужно получить
}

// Ответ с информацией о пользователях
message GetUsersByIDsResponse {
  repeated User users = 1; // Список сообщений User
}