// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/memory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_UNSPECIFIED MediaType = 0 // Always include UNSPECIFIED as the first value
	MediaType_image       MediaType = 1
	MediaType_video       MediaType = 2
	MediaType_quote       MediaType = 3
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "image",
		2: "video",
		3: "quote",
	}
	MediaType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"image":       1,
		"video":       2,
		"quote":       3,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_memory_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_proto_memory_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{0}
}

// Модель воспоминания
type Memory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaType     MediaType              `protobuf:"varint,4,opt,name=media_type,json=mediaType,proto3,enum=memory.MediaType" json:"media_type,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,5,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	Latitude      float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	MusicId       string                 `protobuf:"bytes,8,opt,name=music_id,json=musicId,proto3" json:"music_id,omitempty"`
	Offset        float64                `protobuf:"fixed64,9,opt,name=offset,proto3" json:"offset,omitempty"`
	Duration      float64                `protobuf:"fixed64,10,opt,name=duration,proto3" json:"duration,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memory) Reset() {
	*x = Memory{}
	mi := &file_proto_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memory) ProtoMessage() {}

func (x *Memory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memory.ProtoReflect.Descriptor instead.
func (*Memory) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{0}
}

func (x *Memory) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Memory) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *Memory) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Memory) GetMediaType() MediaType {
	if x != nil {
		return x.MediaType
	}
	return MediaType_UNSPECIFIED
}

func (x *Memory) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *Memory) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Memory) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Memory) GetMusicId() string {
	if x != nil {
		return x.MusicId
	}
	return ""
}

func (x *Memory) GetOffset() float64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Memory) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Memory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Memory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Модель тега воспоминания
type MemoryTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MemoryId      uint64                 `protobuf:"varint,2,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryTag) Reset() {
	*x = MemoryTag{}
	mi := &file_proto_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryTag) ProtoMessage() {}

func (x *MemoryTag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryTag.ProtoReflect.Descriptor instead.
func (*MemoryTag) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{1}
}

func (x *MemoryTag) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemoryTag) GetMemoryId() uint64 {
	if x != nil {
		return x.MemoryId
	}
	return 0
}

func (x *MemoryTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemoryTag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MemoryTag) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Модель избранного
type Favourite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      uint64                 `protobuf:"varint,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Favourite) Reset() {
	*x = Favourite{}
	mi := &file_proto_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Favourite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Favourite) ProtoMessage() {}

func (x *Favourite) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Favourite.ProtoReflect.Descriptor instead.
func (*Favourite) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{2}
}

func (x *Favourite) GetMemoryId() uint64 {
	if x != nil {
		return x.MemoryId
	}
	return 0
}

func (x *Favourite) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Favourite) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Запрос на создание воспоминания
type CreateMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaType     MediaType              `protobuf:"varint,3,opt,name=media_type,json=mediaType,proto3,enum=memory.MediaType" json:"media_type,omitempty"`
	MediaFile     []byte                 `protobuf:"bytes,4,opt,name=media_file,json=mediaFile,proto3" json:"media_file,omitempty"`
	Latitude      *float64               `protobuf:"fixed64,5,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude     *float64               `protobuf:"fixed64,6,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	MusicId       *string                `protobuf:"bytes,7,opt,name=music_id,json=musicId,proto3,oneof" json:"music_id,omitempty"`
	Offset        *float64               `protobuf:"fixed64,8,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	Duration      *float64               `protobuf:"fixed64,9,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	Tags          []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoryRequest) Reset() {
	*x = CreateMemoryRequest{}
	mi := &file_proto_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoryRequest) ProtoMessage() {}

func (x *CreateMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoryRequest.ProtoReflect.Descriptor instead.
func (*CreateMemoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMemoryRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateMemoryRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateMemoryRequest) GetMediaType() MediaType {
	if x != nil {
		return x.MediaType
	}
	return MediaType_UNSPECIFIED
}

func (x *CreateMemoryRequest) GetMediaFile() []byte {
	if x != nil {
		return x.MediaFile
	}
	return nil
}

func (x *CreateMemoryRequest) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *CreateMemoryRequest) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *CreateMemoryRequest) GetMusicId() string {
	if x != nil && x.MusicId != nil {
		return *x.MusicId
	}
	return ""
}

func (x *CreateMemoryRequest) GetOffset() float64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *CreateMemoryRequest) GetDuration() float64 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *CreateMemoryRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Ответ на создание воспоминания
type CreateMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *Memory                `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoryResponse) Reset() {
	*x = CreateMemoryResponse{}
	mi := &file_proto_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoryResponse) ProtoMessage() {}

func (x *CreateMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoryResponse.ProtoReflect.Descriptor instead.
func (*CreateMemoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMemoryResponse) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

type GetMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      uint64                 `protobuf:"varint,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryRequest) Reset() {
	*x = GetMemoryRequest{}
	mi := &file_proto_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryRequest) ProtoMessage() {}

func (x *GetMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryRequest.ProtoReflect.Descriptor instead.
func (*GetMemoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{5}
}

func (x *GetMemoryRequest) GetMemoryId() uint64 {
	if x != nil {
		return x.MemoryId
	}
	return 0
}

func (x *GetMemoryRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *DetailedMemory        `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryResponse) Reset() {
	*x = GetMemoryResponse{}
	mi := &file_proto_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryResponse) ProtoMessage() {}

func (x *GetMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryResponse.ProtoReflect.Descriptor instead.
func (*GetMemoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{6}
}

func (x *GetMemoryResponse) GetMemory() *DetailedMemory {
	if x != nil {
		return x.Memory
	}
	return nil
}

// Запрос на удаление воспоминаний по Group ID
type DeleteMemoriesByGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoriesByGroupRequest) Reset() {
	*x = DeleteMemoriesByGroupRequest{}
	mi := &file_proto_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoriesByGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoriesByGroupRequest) ProtoMessage() {}

func (x *DeleteMemoriesByGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoriesByGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemoriesByGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMemoriesByGroupRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// Ответ на удаление воспоминаний по Group ID
type DeleteMemoriesByGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoriesByGroupResponse) Reset() {
	*x = DeleteMemoriesByGroupResponse{}
	mi := &file_proto_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoriesByGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoriesByGroupResponse) ProtoMessage() {}

func (x *DeleteMemoriesByGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoriesByGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteMemoriesByGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMemoriesByGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос на удаление воспоминания
type DeleteMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      uint64                 `protobuf:"varint,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryRequest) Reset() {
	*x = DeleteMemoryRequest{}
	mi := &file_proto_memory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryRequest) ProtoMessage() {}

func (x *DeleteMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMemoryRequest) GetMemoryId() uint64 {
	if x != nil {
		return x.MemoryId
	}
	return 0
}

func (x *DeleteMemoryRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteMemoryRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

// Ответ на удаление воспоминания
type DeleteMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryResponse) Reset() {
	*x = DeleteMemoryResponse{}
	mi := &file_proto_memory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryResponse) ProtoMessage() {}

func (x *DeleteMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteMemoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMemoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос на получение списка воспоминаний по Group ID
type ListMemoriesByGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Для определения, добавлено ли в избранное
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemoriesByGroupRequest) Reset() {
	*x = ListMemoriesByGroupRequest{}
	mi := &file_proto_memory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoriesByGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoriesByGroupRequest) ProtoMessage() {}

func (x *ListMemoriesByGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoriesByGroupRequest.ProtoReflect.Descriptor instead.
func (*ListMemoriesByGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{11}
}

func (x *ListMemoriesByGroupRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ListMemoriesByGroupRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Ответ на получение списка воспоминаний по Group ID (с детальной информацией)
type ListMemoriesByGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memories      []*DetailedMemory      `protobuf:"bytes,1,rep,name=memories,proto3" json:"memories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemoriesByGroupResponse) Reset() {
	*x = ListMemoriesByGroupResponse{}
	mi := &file_proto_memory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoriesByGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoriesByGroupResponse) ProtoMessage() {}

func (x *ListMemoriesByGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoriesByGroupResponse.ProtoReflect.Descriptor instead.
func (*ListMemoriesByGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{12}
}

func (x *ListMemoriesByGroupResponse) GetMemories() []*DetailedMemory {
	if x != nil {
		return x.Memories
	}
	return nil
}

// Запрос на получение списка воспоминаний по Group ID с фильтрами
type ListMemoriesByGroupWithFiltersRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupId          uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId           uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                              // Для определения, добавлено ли в избранное
	Filters          map[string]string      `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Пример: {"created_at_gte": "2023-01-01", "user_id": "123"}
	NumberOfMemories uint64                 `protobuf:"varint,4,opt,name=number_of_memories,json=numberOfMemories,proto3" json:"number_of_memories,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListMemoriesByGroupWithFiltersRequest) Reset() {
	*x = ListMemoriesByGroupWithFiltersRequest{}
	mi := &file_proto_memory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoriesByGroupWithFiltersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoriesByGroupWithFiltersRequest) ProtoMessage() {}

func (x *ListMemoriesByGroupWithFiltersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoriesByGroupWithFiltersRequest.ProtoReflect.Descriptor instead.
func (*ListMemoriesByGroupWithFiltersRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{13}
}

func (x *ListMemoriesByGroupWithFiltersRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ListMemoriesByGroupWithFiltersRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListMemoriesByGroupWithFiltersRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListMemoriesByGroupWithFiltersRequest) GetNumberOfMemories() uint64 {
	if x != nil {
		return x.NumberOfMemories
	}
	return 0
}

// Ответ на получение списка воспоминаний по Group ID с фильтрами (с детальной информацией)
type ListMemoriesByGroupWithFiltersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memories      []*DetailedMemory      `protobuf:"bytes,1,rep,name=memories,proto3" json:"memories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemoriesByGroupWithFiltersResponse) Reset() {
	*x = ListMemoriesByGroupWithFiltersResponse{}
	mi := &file_proto_memory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoriesByGroupWithFiltersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoriesByGroupWithFiltersResponse) ProtoMessage() {}

func (x *ListMemoriesByGroupWithFiltersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoriesByGroupWithFiltersResponse.ProtoReflect.Descriptor instead.
func (*ListMemoriesByGroupWithFiltersResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{14}
}

func (x *ListMemoriesByGroupWithFiltersResponse) GetMemories() []*DetailedMemory {
	if x != nil {
		return x.Memories
	}
	return nil
}

// Детальная информация о воспоминании (включая теги и статус избранного)
type DetailedMemory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *Memory                `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	IsFavourite   bool                   `protobuf:"varint,3,opt,name=is_favourite,json=isFavourite,proto3" json:"is_favourite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailedMemory) Reset() {
	*x = DetailedMemory{}
	mi := &file_proto_memory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailedMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailedMemory) ProtoMessage() {}

func (x *DetailedMemory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailedMemory.ProtoReflect.Descriptor instead.
func (*DetailedMemory) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{15}
}

func (x *DetailedMemory) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *DetailedMemory) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DetailedMemory) GetIsFavourite() bool {
	if x != nil {
		return x.IsFavourite
	}
	return false
}

// Запрос на создание тега воспоминания
type CreateMemoryTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      uint64                 `protobuf:"varint,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoryTagRequest) Reset() {
	*x = CreateMemoryTagRequest{}
	mi := &file_proto_memory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoryTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoryTagRequest) ProtoMessage() {}

func (x *CreateMemoryTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoryTagRequest.ProtoReflect.Descriptor instead.
func (*CreateMemoryTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{16}
}

func (x *CreateMemoryTagRequest) GetMemoryId() uint64 {
	if x != nil {
		return x.MemoryId
	}
	return 0
}

func (x *CreateMemoryTagRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateMemoryTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Ответ на создание тега воспоминания
type CreateMemoryTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *MemoryTag             `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoryTagResponse) Reset() {
	*x = CreateMemoryTagResponse{}
	mi := &file_proto_memory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoryTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoryTagResponse) ProtoMessage() {}

func (x *CreateMemoryTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoryTagResponse.ProtoReflect.Descriptor instead.
func (*CreateMemoryTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{17}
}

func (x *CreateMemoryTagResponse) GetTag() *MemoryTag {
	if x != nil {
		return x.Tag
	}
	return nil
}

// Запрос на удаление тега воспоминания
type DeleteMemoryTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      uint64                 `protobuf:"varint,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryTagRequest) Reset() {
	*x = DeleteMemoryTagRequest{}
	mi := &file_proto_memory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryTagRequest) ProtoMessage() {}

func (x *DeleteMemoryTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemoryTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteMemoryTagRequest) GetMemoryId() uint64 {
	if x != nil {
		return x.MemoryId
	}
	return 0
}

func (x *DeleteMemoryTagRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *DeleteMemoryTagRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// Ответ на удаление тега воспоминания
type DeleteMemoryTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryTagResponse) Reset() {
	*x = DeleteMemoryTagResponse{}
	mi := &file_proto_memory_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryTagResponse) ProtoMessage() {}

func (x *DeleteMemoryTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteMemoryTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteMemoryTagResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос на получение списка тегов воспоминания по ID воспоминания
type ListMemoryTagsByMemoryIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      uint64                 `protobuf:"varint,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemoryTagsByMemoryIDRequest) Reset() {
	*x = ListMemoryTagsByMemoryIDRequest{}
	mi := &file_proto_memory_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoryTagsByMemoryIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoryTagsByMemoryIDRequest) ProtoMessage() {}

func (x *ListMemoryTagsByMemoryIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoryTagsByMemoryIDRequest.ProtoReflect.Descriptor instead.
func (*ListMemoryTagsByMemoryIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{20}
}

func (x *ListMemoryTagsByMemoryIDRequest) GetMemoryId() uint64 {
	if x != nil {
		return x.MemoryId
	}
	return 0
}

func (x *ListMemoryTagsByMemoryIDRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// Ответ на получение списка тегов воспоминания по ID воспоминания
type ListMemoryTagsByMemoryIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*MemoryTag           `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemoryTagsByMemoryIDResponse) Reset() {
	*x = ListMemoryTagsByMemoryIDResponse{}
	mi := &file_proto_memory_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoryTagsByMemoryIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoryTagsByMemoryIDResponse) ProtoMessage() {}

func (x *ListMemoryTagsByMemoryIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoryTagsByMemoryIDResponse.ProtoReflect.Descriptor instead.
func (*ListMemoryTagsByMemoryIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{21}
}

func (x *ListMemoryTagsByMemoryIDResponse) GetTags() []*MemoryTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Запрос на создание избранного
type CreateFavouriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      uint64                 `protobuf:"varint,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFavouriteRequest) Reset() {
	*x = CreateFavouriteRequest{}
	mi := &file_proto_memory_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFavouriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFavouriteRequest) ProtoMessage() {}

func (x *CreateFavouriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFavouriteRequest.ProtoReflect.Descriptor instead.
func (*CreateFavouriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{22}
}

func (x *CreateFavouriteRequest) GetMemoryId() uint64 {
	if x != nil {
		return x.MemoryId
	}
	return 0
}

func (x *CreateFavouriteRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Ответ на создание избранного
type CreateFavouriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Favourite     *Favourite             `protobuf:"bytes,1,opt,name=favourite,proto3" json:"favourite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFavouriteResponse) Reset() {
	*x = CreateFavouriteResponse{}
	mi := &file_proto_memory_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFavouriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFavouriteResponse) ProtoMessage() {}

func (x *CreateFavouriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFavouriteResponse.ProtoReflect.Descriptor instead.
func (*CreateFavouriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{23}
}

func (x *CreateFavouriteResponse) GetFavourite() *Favourite {
	if x != nil {
		return x.Favourite
	}
	return nil
}

// Запрос на удаление избранного
type DeleteFavouriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      uint64                 `protobuf:"varint,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFavouriteRequest) Reset() {
	*x = DeleteFavouriteRequest{}
	mi := &file_proto_memory_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFavouriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFavouriteRequest) ProtoMessage() {}

func (x *DeleteFavouriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFavouriteRequest.ProtoReflect.Descriptor instead.
func (*DeleteFavouriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteFavouriteRequest) GetMemoryId() uint64 {
	if x != nil {
		return x.MemoryId
	}
	return 0
}

func (x *DeleteFavouriteRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Ответ на удаление избранного
type DeleteFavouriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFavouriteResponse) Reset() {
	*x = DeleteFavouriteResponse{}
	mi := &file_proto_memory_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFavouriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFavouriteResponse) ProtoMessage() {}

func (x *DeleteFavouriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFavouriteResponse.ProtoReflect.Descriptor instead.
func (*DeleteFavouriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteFavouriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос на удаление избранного для пользователя
type DeleteFavouritedByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFavouritedByUserIDRequest) Reset() {
	*x = DeleteFavouritedByUserIDRequest{}
	mi := &file_proto_memory_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFavouritedByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFavouritedByUserIDRequest) ProtoMessage() {}

func (x *DeleteFavouritedByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFavouritedByUserIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteFavouritedByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteFavouritedByUserIDRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Ответ на удаление избранного для пользователя
type DeleteFavouritedByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFavouritedByUserIDResponse) Reset() {
	*x = DeleteFavouritedByUserIDResponse{}
	mi := &file_proto_memory_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFavouritedByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFavouritedByUserIDResponse) ProtoMessage() {}

func (x *DeleteFavouritedByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFavouritedByUserIDResponse.ProtoReflect.Descriptor instead.
func (*DeleteFavouritedByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteFavouritedByUserIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_memory_proto protoreflect.FileDescriptor

const file_proto_memory_proto_rawDesc = "" +
	"\n" +
	"\x12proto/memory.proto\x12\x06memory\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x03\n" +
	"\x06Memory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x120\n" +
	"\n" +
	"media_type\x18\x04 \x01(\x0e2\x11.memory.MediaTypeR\tmediaType\x12\x1b\n" +
	"\tmedia_url\x18\x05 \x01(\tR\bmediaUrl\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12\x19\n" +
	"\bmusic_id\x18\b \x01(\tR\amusicId\x12\x16\n" +
	"\x06offset\x18\t \x01(\x01R\x06offset\x12\x1a\n" +
	"\bduration\x18\n" +
	" \x01(\x01R\bduration\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc2\x01\n" +
	"\tMemoryTag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tmemory_id\x18\x02 \x01(\x04R\bmemoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"|\n" +
	"\tFavourite\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\x04R\bmemoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x90\x03\n" +
	"\x13CreateMemoryRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x120\n" +
	"\n" +
	"media_type\x18\x03 \x01(\x0e2\x11.memory.MediaTypeR\tmediaType\x12\x1d\n" +
	"\n" +
	"media_file\x18\x04 \x01(\fR\tmediaFile\x12\x1f\n" +
	"\blatitude\x18\x05 \x01(\x01H\x00R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\x06 \x01(\x01H\x01R\tlongitude\x88\x01\x01\x12\x1e\n" +
	"\bmusic_id\x18\a \x01(\tH\x02R\amusicId\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\b \x01(\x01H\x03R\x06offset\x88\x01\x01\x12\x1f\n" +
	"\bduration\x18\t \x01(\x01H\x04R\bduration\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tagsB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitudeB\v\n" +
	"\t_music_idB\t\n" +
	"\a_offsetB\v\n" +
	"\t_duration\">\n" +
	"\x14CreateMemoryResponse\x12&\n" +
	"\x06memory\x18\x01 \x01(\v2\x0e.memory.MemoryR\x06memory\"H\n" +
	"\x10GetMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\x04R\bmemoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"C\n" +
	"\x11GetMemoryResponse\x12.\n" +
	"\x06memory\x18\x01 \x01(\v2\x16.memory.DetailedMemoryR\x06memory\"9\n" +
	"\x1cDeleteMemoriesByGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\"9\n" +
	"\x1dDeleteMemoriesByGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"f\n" +
	"\x13DeleteMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\x04R\bmemoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\bR\aisAdmin\"0\n" +
	"\x14DeleteMemoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"P\n" +
	"\x1aListMemoriesByGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"Q\n" +
	"\x1bListMemoriesByGroupResponse\x122\n" +
	"\bmemories\x18\x01 \x03(\v2\x16.memory.DetailedMemoryR\bmemories\"\x9b\x02\n" +
	"%ListMemoriesByGroupWithFiltersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12T\n" +
	"\afilters\x18\x03 \x03(\v2:.memory.ListMemoriesByGroupWithFiltersRequest.FiltersEntryR\afilters\x12,\n" +
	"\x12number_of_memories\x18\x04 \x01(\x04R\x10numberOfMemories\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"&ListMemoriesByGroupWithFiltersResponse\x122\n" +
	"\bmemories\x18\x01 \x03(\v2\x16.memory.DetailedMemoryR\bmemories\"o\n" +
	"\x0eDetailedMemory\x12&\n" +
	"\x06memory\x18\x01 \x01(\v2\x0e.memory.MemoryR\x06memory\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12!\n" +
	"\fis_favourite\x18\x03 \x01(\bR\visFavourite\"d\n" +
	"\x16CreateMemoryTagRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\x04R\bmemoryId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\">\n" +
	"\x17CreateMemoryTagResponse\x12#\n" +
	"\x03tag\x18\x01 \x01(\v2\x11.memory.MemoryTagR\x03tag\"b\n" +
	"\x16DeleteMemoryTagRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\x04R\bmemoryId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\"3\n" +
	"\x17DeleteMemoryTagResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Y\n" +
	"\x1fListMemoryTagsByMemoryIDRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\x04R\bmemoryId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\"I\n" +
	" ListMemoryTagsByMemoryIDResponse\x12%\n" +
	"\x04tags\x18\x01 \x03(\v2\x11.memory.MemoryTagR\x04tags\"N\n" +
	"\x16CreateFavouriteRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\x04R\bmemoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"J\n" +
	"\x17CreateFavouriteResponse\x12/\n" +
	"\tfavourite\x18\x01 \x01(\v2\x11.memory.FavouriteR\tfavourite\"N\n" +
	"\x16DeleteFavouriteRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\x04R\bmemoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"3\n" +
	"\x17DeleteFavouriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\":\n" +
	"\x1fDeleteFavouritedByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"<\n" +
	" DeleteFavouritedByUserIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*=\n" +
	"\tMediaType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\t\n" +
	"\x05image\x10\x01\x12\t\n" +
	"\x05video\x10\x02\x12\t\n" +
	"\x05quote\x10\x032\xdc\b\n" +
	"\rMemoryService\x12I\n" +
	"\fCreateMemory\x12\x1b.memory.CreateMemoryRequest\x1a\x1c.memory.CreateMemoryResponse\x12@\n" +
	"\tGetMemory\x12\x18.memory.GetMemoryRequest\x1a\x19.memory.GetMemoryResponse\x12I\n" +
	"\fDeleteMemory\x12\x1b.memory.DeleteMemoryRequest\x1a\x1c.memory.DeleteMemoryResponse\x12d\n" +
	"\x15DeleteMemoriesByGroup\x12$.memory.DeleteMemoriesByGroupRequest\x1a%.memory.DeleteMemoriesByGroupResponse\x12^\n" +
	"\x13ListMemoriesByGroup\x12\".memory.ListMemoriesByGroupRequest\x1a#.memory.ListMemoriesByGroupResponse\x12\x7f\n" +
	"\x1eListMemoriesByGroupWithFilters\x12-.memory.ListMemoriesByGroupWithFiltersRequest\x1a..memory.ListMemoriesByGroupWithFiltersResponse\x12R\n" +
	"\x0fCreateMemoryTag\x12\x1e.memory.CreateMemoryTagRequest\x1a\x1f.memory.CreateMemoryTagResponse\x12R\n" +
	"\x0fDeleteMemoryTag\x12\x1e.memory.DeleteMemoryTagRequest\x1a\x1f.memory.DeleteMemoryTagResponse\x12m\n" +
	"\x18ListMemoryTagsByMemoryID\x12'.memory.ListMemoryTagsByMemoryIDRequest\x1a(.memory.ListMemoryTagsByMemoryIDResponse\x12R\n" +
	"\x0fCreateFavourite\x12\x1e.memory.CreateFavouriteRequest\x1a\x1f.memory.CreateFavouriteResponse\x12R\n" +
	"\x0fDeleteFavourite\x12\x1e.memory.DeleteFavouriteRequest\x1a\x1f.memory.DeleteFavouriteResponse\x12m\n" +
	"\x18DeleteFavouritesByUserID\x12'.memory.DeleteFavouritedByUserIDRequest\x1a(.memory.DeleteFavouritedByUserIDResponseB)Z'Rewind-2.0/Backend/memory-service/protob\x06proto3"

var (
	file_proto_memory_proto_rawDescOnce sync.Once
	file_proto_memory_proto_rawDescData []byte
)

func file_proto_memory_proto_rawDescGZIP() []byte {
	file_proto_memory_proto_rawDescOnce.Do(func() {
		file_proto_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_memory_proto_rawDesc), len(file_proto_memory_proto_rawDesc)))
	})
	return file_proto_memory_proto_rawDescData
}

var file_proto_memory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_memory_proto_goTypes = []any{
	(MediaType)(0),                                 // 0: memory.MediaType
	(*Memory)(nil),                                 // 1: memory.Memory
	(*MemoryTag)(nil),                              // 2: memory.MemoryTag
	(*Favourite)(nil),                              // 3: memory.Favourite
	(*CreateMemoryRequest)(nil),                    // 4: memory.CreateMemoryRequest
	(*CreateMemoryResponse)(nil),                   // 5: memory.CreateMemoryResponse
	(*GetMemoryRequest)(nil),                       // 6: memory.GetMemoryRequest
	(*GetMemoryResponse)(nil),                      // 7: memory.GetMemoryResponse
	(*DeleteMemoriesByGroupRequest)(nil),           // 8: memory.DeleteMemoriesByGroupRequest
	(*DeleteMemoriesByGroupResponse)(nil),          // 9: memory.DeleteMemoriesByGroupResponse
	(*DeleteMemoryRequest)(nil),                    // 10: memory.DeleteMemoryRequest
	(*DeleteMemoryResponse)(nil),                   // 11: memory.DeleteMemoryResponse
	(*ListMemoriesByGroupRequest)(nil),             // 12: memory.ListMemoriesByGroupRequest
	(*ListMemoriesByGroupResponse)(nil),            // 13: memory.ListMemoriesByGroupResponse
	(*ListMemoriesByGroupWithFiltersRequest)(nil),  // 14: memory.ListMemoriesByGroupWithFiltersRequest
	(*ListMemoriesByGroupWithFiltersResponse)(nil), // 15: memory.ListMemoriesByGroupWithFiltersResponse
	(*DetailedMemory)(nil),                         // 16: memory.DetailedMemory
	(*CreateMemoryTagRequest)(nil),                 // 17: memory.CreateMemoryTagRequest
	(*CreateMemoryTagResponse)(nil),                // 18: memory.CreateMemoryTagResponse
	(*DeleteMemoryTagRequest)(nil),                 // 19: memory.DeleteMemoryTagRequest
	(*DeleteMemoryTagResponse)(nil),                // 20: memory.DeleteMemoryTagResponse
	(*ListMemoryTagsByMemoryIDRequest)(nil),        // 21: memory.ListMemoryTagsByMemoryIDRequest
	(*ListMemoryTagsByMemoryIDResponse)(nil),       // 22: memory.ListMemoryTagsByMemoryIDResponse
	(*CreateFavouriteRequest)(nil),                 // 23: memory.CreateFavouriteRequest
	(*CreateFavouriteResponse)(nil),                // 24: memory.CreateFavouriteResponse
	(*DeleteFavouriteRequest)(nil),                 // 25: memory.DeleteFavouriteRequest
	(*DeleteFavouriteResponse)(nil),                // 26: memory.DeleteFavouriteResponse
	(*DeleteFavouritedByUserIDRequest)(nil),        // 27: memory.DeleteFavouritedByUserIDRequest
	(*DeleteFavouritedByUserIDResponse)(nil),       // 28: memory.DeleteFavouritedByUserIDResponse
	nil,                                            // 29: memory.ListMemoriesByGroupWithFiltersRequest.FiltersEntry
	(*timestamppb.Timestamp)(nil),                  // 30: google.protobuf.Timestamp
}
var file_proto_memory_proto_depIdxs = []int32{
	0,  // 0: memory.Memory.media_type:type_name -> memory.MediaType
	30, // 1: memory.Memory.created_at:type_name -> google.protobuf.Timestamp
	30, // 2: memory.Memory.updated_at:type_name -> google.protobuf.Timestamp
	30, // 3: memory.MemoryTag.created_at:type_name -> google.protobuf.Timestamp
	30, // 4: memory.MemoryTag.updated_at:type_name -> google.protobuf.Timestamp
	30, // 5: memory.Favourite.created_at:type_name -> google.protobuf.Timestamp
	0,  // 6: memory.CreateMemoryRequest.media_type:type_name -> memory.MediaType
	1,  // 7: memory.CreateMemoryResponse.memory:type_name -> memory.Memory
	16, // 8: memory.GetMemoryResponse.memory:type_name -> memory.DetailedMemory
	16, // 9: memory.ListMemoriesByGroupResponse.memories:type_name -> memory.DetailedMemory
	29, // 10: memory.ListMemoriesByGroupWithFiltersRequest.filters:type_name -> memory.ListMemoriesByGroupWithFiltersRequest.FiltersEntry
	16, // 11: memory.ListMemoriesByGroupWithFiltersResponse.memories:type_name -> memory.DetailedMemory
	1,  // 12: memory.DetailedMemory.memory:type_name -> memory.Memory
	2,  // 13: memory.CreateMemoryTagResponse.tag:type_name -> memory.MemoryTag
	2,  // 14: memory.ListMemoryTagsByMemoryIDResponse.tags:type_name -> memory.MemoryTag
	3,  // 15: memory.CreateFavouriteResponse.favourite:type_name -> memory.Favourite
	4,  // 16: memory.MemoryService.CreateMemory:input_type -> memory.CreateMemoryRequest
	6,  // 17: memory.MemoryService.GetMemory:input_type -> memory.GetMemoryRequest
	10, // 18: memory.MemoryService.DeleteMemory:input_type -> memory.DeleteMemoryRequest
	8,  // 19: memory.MemoryService.DeleteMemoriesByGroup:input_type -> memory.DeleteMemoriesByGroupRequest
	12, // 20: memory.MemoryService.ListMemoriesByGroup:input_type -> memory.ListMemoriesByGroupRequest
	14, // 21: memory.MemoryService.ListMemoriesByGroupWithFilters:input_type -> memory.ListMemoriesByGroupWithFiltersRequest
	17, // 22: memory.MemoryService.CreateMemoryTag:input_type -> memory.CreateMemoryTagRequest
	19, // 23: memory.MemoryService.DeleteMemoryTag:input_type -> memory.DeleteMemoryTagRequest
	21, // 24: memory.MemoryService.ListMemoryTagsByMemoryID:input_type -> memory.ListMemoryTagsByMemoryIDRequest
	23, // 25: memory.MemoryService.CreateFavourite:input_type -> memory.CreateFavouriteRequest
	25, // 26: memory.MemoryService.DeleteFavourite:input_type -> memory.DeleteFavouriteRequest
	27, // 27: memory.MemoryService.DeleteFavouritesByUserID:input_type -> memory.DeleteFavouritedByUserIDRequest
	5,  // 28: memory.MemoryService.CreateMemory:output_type -> memory.CreateMemoryResponse
	7,  // 29: memory.MemoryService.GetMemory:output_type -> memory.GetMemoryResponse
	11, // 30: memory.MemoryService.DeleteMemory:output_type -> memory.DeleteMemoryResponse
	9,  // 31: memory.MemoryService.DeleteMemoriesByGroup:output_type -> memory.DeleteMemoriesByGroupResponse
	13, // 32: memory.MemoryService.ListMemoriesByGroup:output_type -> memory.ListMemoriesByGroupResponse
	15, // 33: memory.MemoryService.ListMemoriesByGroupWithFilters:output_type -> memory.ListMemoriesByGroupWithFiltersResponse
	18, // 34: memory.MemoryService.CreateMemoryTag:output_type -> memory.CreateMemoryTagResponse
	20, // 35: memory.MemoryService.DeleteMemoryTag:output_type -> memory.DeleteMemoryTagResponse
	22, // 36: memory.MemoryService.ListMemoryTagsByMemoryID:output_type -> memory.ListMemoryTagsByMemoryIDResponse
	24, // 37: memory.MemoryService.CreateFavourite:output_type -> memory.CreateFavouriteResponse
	26, // 38: memory.MemoryService.DeleteFavourite:output_type -> memory.DeleteFavouriteResponse
	28, // 39: memory.MemoryService.DeleteFavouritesByUserID:output_type -> memory.DeleteFavouritedByUserIDResponse
	28, // [28:40] is the sub-list for method output_type
	16, // [16:28] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_memory_proto_init() }
func file_proto_memory_proto_init() {
	if File_proto_memory_proto != nil {
		return
	}
	file_proto_memory_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_memory_proto_rawDesc), len(file_proto_memory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_memory_proto_goTypes,
		DependencyIndexes: file_proto_memory_proto_depIdxs,
		EnumInfos:         file_proto_memory_proto_enumTypes,
		MessageInfos:      file_proto_memory_proto_msgTypes,
	}.Build()
	File_proto_memory_proto = out.File
	file_proto_memory_proto_goTypes = nil
	file_proto_memory_proto_depIdxs = nil
}
