// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/clients/auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_clients_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type StartRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRegistrationRequest) Reset() {
	*x = StartRegistrationRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRegistrationRequest) ProtoMessage() {}

func (x *StartRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRegistrationRequest.ProtoReflect.Descriptor instead.
func (*StartRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{1}
}

func (x *StartRegistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type StartRegistrationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"` // Unique ID to track the registration process
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartRegistrationResponse) Reset() {
	*x = StartRegistrationResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRegistrationResponse) ProtoMessage() {}

func (x *StartRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRegistrationResponse.ProtoReflect.Descriptor instead.
func (*StartRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{2}
}

func (x *StartRegistrationResponse) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *StartRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VerifyEmailCodeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId   string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	VerificationCode string                 `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifyEmailCodeRequest) Reset() {
	*x = VerifyEmailCodeRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailCodeRequest) ProtoMessage() {}

func (x *VerifyEmailCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailCodeRequest.ProtoReflect.Descriptor instead.
func (*VerifyEmailCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyEmailCodeRequest) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *VerifyEmailCodeRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

type VerifyEmailCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailCodeResponse) Reset() {
	*x = VerifyEmailCodeResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailCodeResponse) ProtoMessage() {}

func (x *VerifyEmailCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailCodeResponse.ProtoReflect.Descriptor instead.
func (*VerifyEmailCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyEmailCodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetPasswordAndUsernameRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	Password       string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Username       string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetPasswordAndUsernameRequest) Reset() {
	*x = SetPasswordAndUsernameRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPasswordAndUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPasswordAndUsernameRequest) ProtoMessage() {}

func (x *SetPasswordAndUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPasswordAndUsernameRequest.ProtoReflect.Descriptor instead.
func (*SetPasswordAndUsernameRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{5}
}

func (x *SetPasswordAndUsernameRequest) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *SetPasswordAndUsernameRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SetPasswordAndUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SetPasswordAndUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPasswordAndUsernameResponse) Reset() {
	*x = SetPasswordAndUsernameResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPasswordAndUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPasswordAndUsernameResponse) ProtoMessage() {}

func (x *SetPasswordAndUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPasswordAndUsernameResponse.ProtoReflect.Descriptor instead.
func (*SetPasswordAndUsernameResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{6}
}

func (x *SetPasswordAndUsernameResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SetPasswordAndUsernameResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{7}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{8}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ForgotPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordRequest) Reset() {
	*x = ForgotPasswordRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordRequest) ProtoMessage() {}

func (x *ForgotPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordRequest.ProtoReflect.Descriptor instead.
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ForgotPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ForgotPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordResponse) Reset() {
	*x = ForgotPasswordResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordResponse) ProtoMessage() {}

func (x *ForgotPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordResponse.ProtoReflect.Descriptor instead.
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{12}
}

func (x *ForgotPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{13}
}

func (x *ResetPasswordRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{14}
}

func (x *ResetPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{15}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{16}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос для получения информации о пользователях по списку их ID
type GetUsersByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []uint64               `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // Список ID пользователей, информацию о которых нужно получить
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIDsRequest) Reset() {
	*x = GetUsersByIDsRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIDsRequest) ProtoMessage() {}

func (x *GetUsersByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetUsersByIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{19}
}

func (x *GetUsersByIDsRequest) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// Ответ с информацией о пользователях
type GetUsersByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"` // Список сообщений User
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIDsResponse) Reset() {
	*x = GetUsersByIDsResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIDsResponse) ProtoMessage() {}

func (x *GetUsersByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetUsersByIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{20}
}

func (x *GetUsersByIDsResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// Запрос для получения информации о пользователе по ID
type GetUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // ID пользователя, информацию о котором нужно получить
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDRequest) Reset() {
	*x = GetUserByIDRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDRequest) ProtoMessage() {}

func (x *GetUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserByIDRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Ответ с информацией о пользователе
type GetUserByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDResponse) Reset() {
	*x = GetUserByIDResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDResponse) ProtoMessage() {}

func (x *GetUserByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserByIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_proto_clients_auth_proto protoreflect.FileDescriptor

const file_proto_clients_auth_proto_rawDesc = "" +
	"\n" +
	"\x18proto/clients/auth.proto\x12\x04auth\"^\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\"0\n" +
	"\x18StartRegistrationRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"^\n" +
	"\x19StartRegistrationResponse\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"n\n" +
	"\x16VerifyEmailCodeRequest\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x12+\n" +
	"\x11verification_code\x18\x02 \x01(\tR\x10verificationCode\"3\n" +
	"\x17VerifyEmailCodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x80\x01\n" +
	"\x1dSetPasswordAndUsernameRequest\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"h\n" +
	"\x1eSetPasswordAndUsernameResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"W\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"9\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"-\n" +
	"\x15ForgotPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"2\n" +
	"\x16ForgotPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"O\n" +
	"\x14ResetPasswordRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"1\n" +
	"\x15ResetPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x11DeleteUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"1\n" +
	"\x14GetUsersByIDsRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x04R\auserIds\"9\n" +
	"\x15GetUsersByIDsResponse\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".auth.UserR\x05users\"-\n" +
	"\x12GetUserByIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"5\n" +
	"\x13GetUserByIDResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".auth.UserR\x04user2\xc2\x06\n" +
	"\vAuthService\x12V\n" +
	"\x11StartRegistration\x12\x1e.auth.StartRegistrationRequest\x1a\x1f.auth.StartRegistrationResponse\"\x00\x12P\n" +
	"\x0fVerifyEmailCode\x12\x1c.auth.VerifyEmailCodeRequest\x1a\x1d.auth.VerifyEmailCodeResponse\"\x00\x12e\n" +
	"\x16SetPasswordAndUsername\x12#.auth.SetPasswordAndUsernameRequest\x1a$.auth.SetPasswordAndUsernameResponse\"\x00\x122\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\"\x00\x12G\n" +
	"\fRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x1a.auth.RefreshTokenResponse\"\x00\x12M\n" +
	"\x0eForgotPassword\x12\x1b.auth.ForgotPasswordRequest\x1a\x1c.auth.ForgotPasswordResponse\"\x00\x12J\n" +
	"\rResetPassword\x12\x1a.auth.ResetPasswordRequest\x1a\x1b.auth.ResetPasswordResponse\"\x00\x125\n" +
	"\x06Logout\x12\x13.auth.LogoutRequest\x1a\x14.auth.LogoutResponse\"\x00\x12A\n" +
	"\n" +
	"DeleteUser\x12\x17.auth.DeleteUserRequest\x1a\x18.auth.DeleteUserResponse\"\x00\x12J\n" +
	"\rGetUsersByIDs\x12\x1a.auth.GetUsersByIDsRequest\x1a\x1b.auth.GetUsersByIDsResponse\"\x00\x12D\n" +
	"\vGetUserByID\x12\x18.auth.GetUserByIDRequest\x1a\x19.auth.GetUserByIDResponse\"\x00B'Z%Rewind-2.0/Backend/auth_service/protob\x06proto3"

var (
	file_proto_clients_auth_proto_rawDescOnce sync.Once
	file_proto_clients_auth_proto_rawDescData []byte
)

func file_proto_clients_auth_proto_rawDescGZIP() []byte {
	file_proto_clients_auth_proto_rawDescOnce.Do(func() {
		file_proto_clients_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_clients_auth_proto_rawDesc), len(file_proto_clients_auth_proto_rawDesc)))
	})
	return file_proto_clients_auth_proto_rawDescData
}

var file_proto_clients_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_clients_auth_proto_goTypes = []any{
	(*User)(nil),                           // 0: auth.User
	(*StartRegistrationRequest)(nil),       // 1: auth.StartRegistrationRequest
	(*StartRegistrationResponse)(nil),      // 2: auth.StartRegistrationResponse
	(*VerifyEmailCodeRequest)(nil),         // 3: auth.VerifyEmailCodeRequest
	(*VerifyEmailCodeResponse)(nil),        // 4: auth.VerifyEmailCodeResponse
	(*SetPasswordAndUsernameRequest)(nil),  // 5: auth.SetPasswordAndUsernameRequest
	(*SetPasswordAndUsernameResponse)(nil), // 6: auth.SetPasswordAndUsernameResponse
	(*LoginRequest)(nil),                   // 7: auth.LoginRequest
	(*LoginResponse)(nil),                  // 8: auth.LoginResponse
	(*RefreshTokenRequest)(nil),            // 9: auth.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),           // 10: auth.RefreshTokenResponse
	(*ForgotPasswordRequest)(nil),          // 11: auth.ForgotPasswordRequest
	(*ForgotPasswordResponse)(nil),         // 12: auth.ForgotPasswordResponse
	(*ResetPasswordRequest)(nil),           // 13: auth.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),          // 14: auth.ResetPasswordResponse
	(*LogoutRequest)(nil),                  // 15: auth.LogoutRequest
	(*LogoutResponse)(nil),                 // 16: auth.LogoutResponse
	(*DeleteUserRequest)(nil),              // 17: auth.DeleteUserRequest
	(*DeleteUserResponse)(nil),             // 18: auth.DeleteUserResponse
	(*GetUsersByIDsRequest)(nil),           // 19: auth.GetUsersByIDsRequest
	(*GetUsersByIDsResponse)(nil),          // 20: auth.GetUsersByIDsResponse
	(*GetUserByIDRequest)(nil),             // 21: auth.GetUserByIDRequest
	(*GetUserByIDResponse)(nil),            // 22: auth.GetUserByIDResponse
}
var file_proto_clients_auth_proto_depIdxs = []int32{
	0,  // 0: auth.GetUsersByIDsResponse.users:type_name -> auth.User
	0,  // 1: auth.GetUserByIDResponse.user:type_name -> auth.User
	1,  // 2: auth.AuthService.StartRegistration:input_type -> auth.StartRegistrationRequest
	3,  // 3: auth.AuthService.VerifyEmailCode:input_type -> auth.VerifyEmailCodeRequest
	5,  // 4: auth.AuthService.SetPasswordAndUsername:input_type -> auth.SetPasswordAndUsernameRequest
	7,  // 5: auth.AuthService.Login:input_type -> auth.LoginRequest
	9,  // 6: auth.AuthService.RefreshToken:input_type -> auth.RefreshTokenRequest
	11, // 7: auth.AuthService.ForgotPassword:input_type -> auth.ForgotPasswordRequest
	13, // 8: auth.AuthService.ResetPassword:input_type -> auth.ResetPasswordRequest
	15, // 9: auth.AuthService.Logout:input_type -> auth.LogoutRequest
	17, // 10: auth.AuthService.DeleteUser:input_type -> auth.DeleteUserRequest
	19, // 11: auth.AuthService.GetUsersByIDs:input_type -> auth.GetUsersByIDsRequest
	21, // 12: auth.AuthService.GetUserByID:input_type -> auth.GetUserByIDRequest
	2,  // 13: auth.AuthService.StartRegistration:output_type -> auth.StartRegistrationResponse
	4,  // 14: auth.AuthService.VerifyEmailCode:output_type -> auth.VerifyEmailCodeResponse
	6,  // 15: auth.AuthService.SetPasswordAndUsername:output_type -> auth.SetPasswordAndUsernameResponse
	8,  // 16: auth.AuthService.Login:output_type -> auth.LoginResponse
	10, // 17: auth.AuthService.RefreshToken:output_type -> auth.RefreshTokenResponse
	12, // 18: auth.AuthService.ForgotPassword:output_type -> auth.ForgotPasswordResponse
	14, // 19: auth.AuthService.ResetPassword:output_type -> auth.ResetPasswordResponse
	16, // 20: auth.AuthService.Logout:output_type -> auth.LogoutResponse
	18, // 21: auth.AuthService.DeleteUser:output_type -> auth.DeleteUserResponse
	20, // 22: auth.AuthService.GetUsersByIDs:output_type -> auth.GetUsersByIDsResponse
	22, // 23: auth.AuthService.GetUserByID:output_type -> auth.GetUserByIDResponse
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_clients_auth_proto_init() }
func file_proto_clients_auth_proto_init() {
	if File_proto_clients_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_clients_auth_proto_rawDesc), len(file_proto_clients_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_clients_auth_proto_goTypes,
		DependencyIndexes: file_proto_clients_auth_proto_depIdxs,
		MessageInfos:      file_proto_clients_auth_proto_msgTypes,
	}.Build()
	File_proto_clients_auth_proto = out.File
	file_proto_clients_auth_proto_goTypes = nil
	file_proto_clients_auth_proto_depIdxs = nil
}
