// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/clients/auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username            string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email               string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Image               string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	MemoriesAddedCount  uint64                 `protobuf:"varint,5,opt,name=memories_added_count,json=memoriesAddedCount,proto3" json:"memories_added_count,omitempty"`
	InvitedMembersCount uint64                 `protobuf:"varint,6,opt,name=invited_members_count,json=invitedMembersCount,proto3" json:"invited_members_count,omitempty"`
	MemoriesViewedCount uint64                 `protobuf:"varint,7,opt,name=memories_viewed_count,json=memoriesViewedCount,proto3" json:"memories_viewed_count,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_clients_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *User) GetMemoriesAddedCount() uint64 {
	if x != nil {
		return x.MemoriesAddedCount
	}
	return 0
}

func (x *User) GetInvitedMembersCount() uint64 {
	if x != nil {
		return x.InvitedMembersCount
	}
	return 0
}

func (x *User) GetMemoriesViewedCount() uint64 {
	if x != nil {
		return x.MemoriesViewedCount
	}
	return 0
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UserAchievement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	IsUnlocked    bool                   `protobuf:"varint,4,opt,name=is_unlocked,json=isUnlocked,proto3" json:"is_unlocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAchievement) Reset() {
	*x = UserAchievement{}
	mi := &file_proto_clients_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAchievement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAchievement) ProtoMessage() {}

func (x *UserAchievement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAchievement.ProtoReflect.Descriptor instead.
func (*UserAchievement) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{1}
}

func (x *UserAchievement) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserAchievement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserAchievement) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UserAchievement) GetIsUnlocked() bool {
	if x != nil {
		return x.IsUnlocked
	}
	return false
}

type StartRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRegistrationRequest) Reset() {
	*x = StartRegistrationRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRegistrationRequest) ProtoMessage() {}

func (x *StartRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRegistrationRequest.ProtoReflect.Descriptor instead.
func (*StartRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{2}
}

func (x *StartRegistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type StartRegistrationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"` // Unique ID to track the registration process
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartRegistrationResponse) Reset() {
	*x = StartRegistrationResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRegistrationResponse) ProtoMessage() {}

func (x *StartRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRegistrationResponse.ProtoReflect.Descriptor instead.
func (*StartRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{3}
}

func (x *StartRegistrationResponse) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *StartRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VerifyEmailCodeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId   string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	VerificationCode string                 `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifyEmailCodeRequest) Reset() {
	*x = VerifyEmailCodeRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailCodeRequest) ProtoMessage() {}

func (x *VerifyEmailCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailCodeRequest.ProtoReflect.Descriptor instead.
func (*VerifyEmailCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyEmailCodeRequest) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *VerifyEmailCodeRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

type VerifyEmailCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailCodeResponse) Reset() {
	*x = VerifyEmailCodeResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailCodeResponse) ProtoMessage() {}

func (x *VerifyEmailCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailCodeResponse.ProtoReflect.Descriptor instead.
func (*VerifyEmailCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyEmailCodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetPasswordAndUsernameRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	Password       string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Username       string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetPasswordAndUsernameRequest) Reset() {
	*x = SetPasswordAndUsernameRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPasswordAndUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPasswordAndUsernameRequest) ProtoMessage() {}

func (x *SetPasswordAndUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPasswordAndUsernameRequest.ProtoReflect.Descriptor instead.
func (*SetPasswordAndUsernameRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{6}
}

func (x *SetPasswordAndUsernameRequest) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *SetPasswordAndUsernameRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SetPasswordAndUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SetPasswordAndUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPasswordAndUsernameResponse) Reset() {
	*x = SetPasswordAndUsernameResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPasswordAndUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPasswordAndUsernameResponse) ProtoMessage() {}

func (x *SetPasswordAndUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPasswordAndUsernameResponse.ProtoReflect.Descriptor instead.
func (*SetPasswordAndUsernameResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{7}
}

func (x *SetPasswordAndUsernameResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SetPasswordAndUsernameResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{8}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{9}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ForgotPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordRequest) Reset() {
	*x = ForgotPasswordRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordRequest) ProtoMessage() {}

func (x *ForgotPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordRequest.ProtoReflect.Descriptor instead.
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{12}
}

func (x *ForgotPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ForgotPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordResponse) Reset() {
	*x = ForgotPasswordResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordResponse) ProtoMessage() {}

func (x *ForgotPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordResponse.ProtoReflect.Descriptor instead.
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{13}
}

func (x *ForgotPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{14}
}

func (x *ResetPasswordRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{15}
}

func (x *ResetPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{16}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{17}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUsersByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []uint64               `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIDsRequest) Reset() {
	*x = GetUsersByIDsRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIDsRequest) ProtoMessage() {}

func (x *GetUsersByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetUsersByIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{20}
}

func (x *GetUsersByIDsRequest) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUsersByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIDsResponse) Reset() {
	*x = GetUsersByIDsResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIDsResponse) ProtoMessage() {}

func (x *GetUsersByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetUsersByIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{21}
}

func (x *GetUsersByIDsResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDRequest) Reset() {
	*x = GetUserByIDRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDRequest) ProtoMessage() {}

func (x *GetUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserByIDRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDResponse) Reset() {
	*x = GetUserByIDResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDResponse) ProtoMessage() {}

func (x *GetUserByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{23}
}

func (x *GetUserByIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewUsername   string                 `protobuf:"bytes,2,opt,name=new_username,json=newUsername,proto3" json:"new_username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsernameRequest) Reset() {
	*x = UpdateUsernameRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameRequest) ProtoMessage() {}

func (x *UpdateUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameRequest.ProtoReflect.Descriptor instead.
func (*UpdateUsernameRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateUsernameRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUsernameRequest) GetNewUsername() string {
	if x != nil {
		return x.NewUsername
	}
	return ""
}

type UpdateUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsernameResponse) Reset() {
	*x = UpdateUsernameResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameResponse) ProtoMessage() {}

func (x *UpdateUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameResponse.ProtoReflect.Descriptor instead.
func (*UpdateUsernameResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateUsernameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPasswordRequest) Reset() {
	*x = CheckPasswordRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPasswordRequest) ProtoMessage() {}

func (x *CheckPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPasswordRequest.ProtoReflect.Descriptor instead.
func (*CheckPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{26}
}

func (x *CheckPasswordRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CheckPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPasswordResponse) Reset() {
	*x = CheckPasswordResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPasswordResponse) ProtoMessage() {}

func (x *CheckPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPasswordResponse.ProtoReflect.Descriptor instead.
func (*CheckPasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{27}
}

func (x *CheckPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewEmail      string                 `protobuf:"bytes,2,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailRequest) Reset() {
	*x = UpdateEmailRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailRequest) ProtoMessage() {}

func (x *UpdateEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateEmailRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateEmailRequest) GetNewEmail() string {
	if x != nil {
		return x.NewEmail
	}
	return ""
}

type UpdateEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailResponse) Reset() {
	*x = UpdateEmailResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailResponse) ProtoMessage() {}

func (x *UpdateEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailResponse.ProtoReflect.Descriptor instead.
func (*UpdateEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VerifyNewEmailCodeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VerificationCode string                 `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifyNewEmailCodeRequest) Reset() {
	*x = VerifyNewEmailCodeRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyNewEmailCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNewEmailCodeRequest) ProtoMessage() {}

func (x *VerifyNewEmailCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNewEmailCodeRequest.ProtoReflect.Descriptor instead.
func (*VerifyNewEmailCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{30}
}

func (x *VerifyNewEmailCodeRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifyNewEmailCodeRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

type VerifyNewEmailCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyNewEmailCodeResponse) Reset() {
	*x = VerifyNewEmailCodeResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyNewEmailCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNewEmailCodeResponse) ProtoMessage() {}

func (x *VerifyNewEmailCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNewEmailCodeResponse.ProtoReflect.Descriptor instead.
func (*VerifyNewEmailCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{31}
}

func (x *VerifyNewEmailCodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Image         []byte                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvatarRequest) Reset() {
	*x = UpdateAvatarRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvatarRequest) ProtoMessage() {}

func (x *UpdateAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvatarRequest.ProtoReflect.Descriptor instead.
func (*UpdateAvatarRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateAvatarRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateAvatarRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type UpdateAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvatarResponse) Reset() {
	*x = UpdateAvatarResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvatarResponse) ProtoMessage() {}

func (x *UpdateAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvatarResponse.ProtoReflect.Descriptor instead.
func (*UpdateAvatarResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateAvatarResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StartPasswordResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPasswordResetRequest) Reset() {
	*x = StartPasswordResetRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPasswordResetRequest) ProtoMessage() {}

func (x *StartPasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPasswordResetRequest.ProtoReflect.Descriptor instead.
func (*StartPasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{34}
}

func (x *StartPasswordResetRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type StartPasswordResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPasswordResetResponse) Reset() {
	*x = StartPasswordResetResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPasswordResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPasswordResetResponse) ProtoMessage() {}

func (x *StartPasswordResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPasswordResetResponse.ProtoReflect.Descriptor instead.
func (*StartPasswordResetResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{35}
}

func (x *StartPasswordResetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VerifyPasswordResetCodeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VerificationCode string                 `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifyPasswordResetCodeRequest) Reset() {
	*x = VerifyPasswordResetCodeRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordResetCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordResetCodeRequest) ProtoMessage() {}

func (x *VerifyPasswordResetCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordResetCodeRequest.ProtoReflect.Descriptor instead.
func (*VerifyPasswordResetCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{36}
}

func (x *VerifyPasswordResetCodeRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifyPasswordResetCodeRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

type VerifyPasswordResetCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasswordResetCodeResponse) Reset() {
	*x = VerifyPasswordResetCodeResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordResetCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordResetCodeResponse) ProtoMessage() {}

func (x *VerifyPasswordResetCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordResetCodeResponse.ProtoReflect.Descriptor instead.
func (*VerifyPasswordResetCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{37}
}

func (x *VerifyPasswordResetCodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetNewPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNewPasswordRequest) Reset() {
	*x = SetNewPasswordRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNewPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNewPasswordRequest) ProtoMessage() {}

func (x *SetNewPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNewPasswordRequest.ProtoReflect.Descriptor instead.
func (*SetNewPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{38}
}

func (x *SetNewPasswordRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetNewPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type SetNewPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNewPasswordResponse) Reset() {
	*x = SetNewPasswordResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNewPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNewPasswordResponse) ProtoMessage() {}

func (x *SetNewPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNewPasswordResponse.ProtoReflect.Descriptor instead.
func (*SetNewPasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{39}
}

func (x *SetNewPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAvatarRequest) Reset() {
	*x = DeleteAvatarRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAvatarRequest) ProtoMessage() {}

func (x *DeleteAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAvatarRequest.ProtoReflect.Descriptor instead.
func (*DeleteAvatarRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{40}
}

func (x *DeleteAvatarRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAvatarResponse) Reset() {
	*x = DeleteAvatarResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAvatarResponse) ProtoMessage() {}

func (x *DeleteAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAvatarResponse.ProtoReflect.Descriptor instead.
func (*DeleteAvatarResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{41}
}

func (x *DeleteAvatarResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserAddedMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAddedMemoryRequest) Reset() {
	*x = UserAddedMemoryRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddedMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddedMemoryRequest) ProtoMessage() {}

func (x *UserAddedMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddedMemoryRequest.ProtoReflect.Descriptor instead.
func (*UserAddedMemoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{42}
}

func (x *UserAddedMemoryRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserAddedMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAddedMemoryResponse) Reset() {
	*x = UserAddedMemoryResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddedMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddedMemoryResponse) ProtoMessage() {}

func (x *UserAddedMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddedMemoryResponse.ProtoReflect.Descriptor instead.
func (*UserAddedMemoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{43}
}

func (x *UserAddedMemoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserInvitedMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInvitedMemberRequest) Reset() {
	*x = UserInvitedMemberRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInvitedMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInvitedMemberRequest) ProtoMessage() {}

func (x *UserInvitedMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInvitedMemberRequest.ProtoReflect.Descriptor instead.
func (*UserInvitedMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{44}
}

func (x *UserInvitedMemberRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserInvitedMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInvitedMemberResponse) Reset() {
	*x = UserInvitedMemberResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInvitedMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInvitedMemberResponse) ProtoMessage() {}

func (x *UserInvitedMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInvitedMemberResponse.ProtoReflect.Descriptor instead.
func (*UserInvitedMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{45}
}

func (x *UserInvitedMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserViewedMemoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserViewedMemoriesRequest) Reset() {
	*x = UserViewedMemoriesRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserViewedMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserViewedMemoriesRequest) ProtoMessage() {}

func (x *UserViewedMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserViewedMemoriesRequest.ProtoReflect.Descriptor instead.
func (*UserViewedMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{46}
}

func (x *UserViewedMemoriesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserViewedMemoriesRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UserViewedMemoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserViewedMemoriesResponse) Reset() {
	*x = UserViewedMemoriesResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserViewedMemoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserViewedMemoriesResponse) ProtoMessage() {}

func (x *UserViewedMemoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserViewedMemoriesResponse.ProtoReflect.Descriptor instead.
func (*UserViewedMemoriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{47}
}

func (x *UserViewedMemoriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserAchievementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAchievementsRequest) Reset() {
	*x = GetUserAchievementsRequest{}
	mi := &file_proto_clients_auth_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAchievementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAchievementsRequest) ProtoMessage() {}

func (x *GetUserAchievementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAchievementsRequest.ProtoReflect.Descriptor instead.
func (*GetUserAchievementsRequest) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{48}
}

func (x *GetUserAchievementsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserAchievementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Achievements  []*UserAchievement     `protobuf:"bytes,1,rep,name=achievements,proto3" json:"achievements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAchievementsResponse) Reset() {
	*x = GetUserAchievementsResponse{}
	mi := &file_proto_clients_auth_proto_msgTypes[49]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAchievementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAchievementsResponse) ProtoMessage() {}

func (x *GetUserAchievementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clients_auth_proto_msgTypes[49]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAchievementsResponse.ProtoReflect.Descriptor instead.
func (*GetUserAchievementsResponse) Descriptor() ([]byte, []int) {
	return file_proto_clients_auth_proto_rawDescGZIP(), []int{49}
}

func (x *GetUserAchievementsResponse) GetAchievements() []*UserAchievement {
	if x != nil {
		return x.Achievements
	}
	return nil
}

var File_proto_clients_auth_proto protoreflect.FileDescriptor

const file_proto_clients_auth_proto_rawDesc = "" +
	"\n" +
	"\x18proto/clients/auth.proto\x12\x04auth\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x120\n" +
	"\x14memories_added_count\x18\x05 \x01(\x04R\x12memoriesAddedCount\x122\n" +
	"\x15invited_members_count\x18\x06 \x01(\x04R\x13invitedMembersCount\x122\n" +
	"\x15memories_viewed_count\x18\a \x01(\x04R\x13memoriesViewedCount\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"j\n" +
	"\x0fUserAchievement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x1f\n" +
	"\vis_unlocked\x18\x04 \x01(\bR\n" +
	"isUnlocked\"0\n" +
	"\x18StartRegistrationRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"^\n" +
	"\x19StartRegistrationResponse\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"n\n" +
	"\x16VerifyEmailCodeRequest\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x12+\n" +
	"\x11verification_code\x18\x02 \x01(\tR\x10verificationCode\"3\n" +
	"\x17VerifyEmailCodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x80\x01\n" +
	"\x1dSetPasswordAndUsernameRequest\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"h\n" +
	"\x1eSetPasswordAndUsernameResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"W\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"9\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"-\n" +
	"\x15ForgotPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"2\n" +
	"\x16ForgotPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"O\n" +
	"\x14ResetPasswordRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"1\n" +
	"\x15ResetPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"1\n" +
	"\x14GetUsersByIDsRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x04R\auserIds\"9\n" +
	"\x15GetUsersByIDsResponse\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".auth.UserR\x05users\"-\n" +
	"\x12GetUserByIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"5\n" +
	"\x13GetUserByIDResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".auth.UserR\x04user\"S\n" +
	"\x15UpdateUsernameRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12!\n" +
	"\fnew_username\x18\x02 \x01(\tR\vnewUsername\"2\n" +
	"\x16UpdateUsernameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\x14CheckPasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"1\n" +
	"\x15CheckPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"J\n" +
	"\x12UpdateEmailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tnew_email\x18\x02 \x01(\tR\bnewEmail\"/\n" +
	"\x13UpdateEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"a\n" +
	"\x19VerifyNewEmailCodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12+\n" +
	"\x11verification_code\x18\x02 \x01(\tR\x10verificationCode\"6\n" +
	"\x1aVerifyNewEmailCodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"D\n" +
	"\x13UpdateAvatarRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\fR\x05image\"0\n" +
	"\x14UpdateAvatarResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\x19StartPasswordResetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"6\n" +
	"\x1aStartPasswordResetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"f\n" +
	"\x1eVerifyPasswordResetCodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12+\n" +
	"\x11verification_code\x18\x02 \x01(\tR\x10verificationCode\";\n" +
	"\x1fVerifyPasswordResetCodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"S\n" +
	"\x15SetNewPasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"2\n" +
	"\x16SetNewPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x13DeleteAvatarRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"0\n" +
	"\x14DeleteAvatarResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"1\n" +
	"\x16UserAddedMemoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"3\n" +
	"\x17UserAddedMemoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x18UserInvitedMemberRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"5\n" +
	"\x19UserInvitedMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"J\n" +
	"\x19UserViewedMemoriesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"6\n" +
	"\x1aUserViewedMemoriesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x1aGetUserAchievementsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"X\n" +
	"\x1bGetUserAchievementsResponse\x129\n" +
	"\fachievements\x18\x01 \x03(\v2\x15.auth.UserAchievementR\fachievements2\x87\x0f\n" +
	"\vAuthService\x12V\n" +
	"\x11StartRegistration\x12\x1e.auth.StartRegistrationRequest\x1a\x1f.auth.StartRegistrationResponse\"\x00\x12P\n" +
	"\x0fVerifyEmailCode\x12\x1c.auth.VerifyEmailCodeRequest\x1a\x1d.auth.VerifyEmailCodeResponse\"\x00\x12e\n" +
	"\x16SetPasswordAndUsername\x12#.auth.SetPasswordAndUsernameRequest\x1a$.auth.SetPasswordAndUsernameResponse\"\x00\x122\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\"\x00\x12G\n" +
	"\fRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x1a.auth.RefreshTokenResponse\"\x00\x12M\n" +
	"\x0eForgotPassword\x12\x1b.auth.ForgotPasswordRequest\x1a\x1c.auth.ForgotPasswordResponse\"\x00\x12J\n" +
	"\rResetPassword\x12\x1a.auth.ResetPasswordRequest\x1a\x1b.auth.ResetPasswordResponse\"\x00\x125\n" +
	"\x06Logout\x12\x13.auth.LogoutRequest\x1a\x14.auth.LogoutResponse\"\x00\x12A\n" +
	"\n" +
	"DeleteUser\x12\x17.auth.DeleteUserRequest\x1a\x18.auth.DeleteUserResponse\"\x00\x12J\n" +
	"\rGetUsersByIDs\x12\x1a.auth.GetUsersByIDsRequest\x1a\x1b.auth.GetUsersByIDsResponse\"\x00\x12D\n" +
	"\vGetUserByID\x12\x18.auth.GetUserByIDRequest\x1a\x19.auth.GetUserByIDResponse\"\x00\x12M\n" +
	"\x0eUpdateUsername\x12\x1b.auth.UpdateUsernameRequest\x1a\x1c.auth.UpdateUsernameResponse\"\x00\x12J\n" +
	"\rCheckPassword\x12\x1a.auth.CheckPasswordRequest\x1a\x1b.auth.CheckPasswordResponse\"\x00\x12D\n" +
	"\vUpdateEmail\x12\x18.auth.UpdateEmailRequest\x1a\x19.auth.UpdateEmailResponse\"\x00\x12Y\n" +
	"\x12VerifyNewEmailCode\x12\x1f.auth.VerifyNewEmailCodeRequest\x1a .auth.VerifyNewEmailCodeResponse\"\x00\x12G\n" +
	"\fUpdateAvatar\x12\x19.auth.UpdateAvatarRequest\x1a\x1a.auth.UpdateAvatarResponse\"\x00\x12Y\n" +
	"\x12StartPasswordReset\x12\x1f.auth.StartPasswordResetRequest\x1a .auth.StartPasswordResetResponse\"\x00\x12h\n" +
	"\x17VerifyPasswordResetCode\x12$.auth.VerifyPasswordResetCodeRequest\x1a%.auth.VerifyPasswordResetCodeResponse\"\x00\x12M\n" +
	"\x0eSetNewPassword\x12\x1b.auth.SetNewPasswordRequest\x1a\x1c.auth.SetNewPasswordResponse\"\x00\x12G\n" +
	"\fDeleteAvatar\x12\x19.auth.DeleteAvatarRequest\x1a\x1a.auth.DeleteAvatarResponse\"\x00\x12P\n" +
	"\x0fUserAddedMemory\x12\x1c.auth.UserAddedMemoryRequest\x1a\x1d.auth.UserAddedMemoryResponse\"\x00\x12V\n" +
	"\x11UserInvitedMember\x12\x1e.auth.UserInvitedMemberRequest\x1a\x1f.auth.UserInvitedMemberResponse\"\x00\x12Y\n" +
	"\x12UserViewedMemories\x12\x1f.auth.UserViewedMemoriesRequest\x1a .auth.UserViewedMemoriesResponse\"\x00\x12\\\n" +
	"\x13GetUserAchievements\x12 .auth.GetUserAchievementsRequest\x1a!.auth.GetUserAchievementsResponse\"\x00B'Z%Rewind-2.0/Backend/auth_service/protob\x06proto3"

var (
	file_proto_clients_auth_proto_rawDescOnce sync.Once
	file_proto_clients_auth_proto_rawDescData []byte
)

func file_proto_clients_auth_proto_rawDescGZIP() []byte {
	file_proto_clients_auth_proto_rawDescOnce.Do(func() {
		file_proto_clients_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_clients_auth_proto_rawDesc), len(file_proto_clients_auth_proto_rawDesc)))
	})
	return file_proto_clients_auth_proto_rawDescData
}

var file_proto_clients_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 50)
var file_proto_clients_auth_proto_goTypes = []any{
	(*User)(nil),                            // 0: auth.User
	(*UserAchievement)(nil),                 // 1: auth.UserAchievement
	(*StartRegistrationRequest)(nil),        // 2: auth.StartRegistrationRequest
	(*StartRegistrationResponse)(nil),       // 3: auth.StartRegistrationResponse
	(*VerifyEmailCodeRequest)(nil),          // 4: auth.VerifyEmailCodeRequest
	(*VerifyEmailCodeResponse)(nil),         // 5: auth.VerifyEmailCodeResponse
	(*SetPasswordAndUsernameRequest)(nil),   // 6: auth.SetPasswordAndUsernameRequest
	(*SetPasswordAndUsernameResponse)(nil),  // 7: auth.SetPasswordAndUsernameResponse
	(*LoginRequest)(nil),                    // 8: auth.LoginRequest
	(*LoginResponse)(nil),                   // 9: auth.LoginResponse
	(*RefreshTokenRequest)(nil),             // 10: auth.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),            // 11: auth.RefreshTokenResponse
	(*ForgotPasswordRequest)(nil),           // 12: auth.ForgotPasswordRequest
	(*ForgotPasswordResponse)(nil),          // 13: auth.ForgotPasswordResponse
	(*ResetPasswordRequest)(nil),            // 14: auth.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),           // 15: auth.ResetPasswordResponse
	(*LogoutRequest)(nil),                   // 16: auth.LogoutRequest
	(*LogoutResponse)(nil),                  // 17: auth.LogoutResponse
	(*DeleteUserRequest)(nil),               // 18: auth.DeleteUserRequest
	(*DeleteUserResponse)(nil),              // 19: auth.DeleteUserResponse
	(*GetUsersByIDsRequest)(nil),            // 20: auth.GetUsersByIDsRequest
	(*GetUsersByIDsResponse)(nil),           // 21: auth.GetUsersByIDsResponse
	(*GetUserByIDRequest)(nil),              // 22: auth.GetUserByIDRequest
	(*GetUserByIDResponse)(nil),             // 23: auth.GetUserByIDResponse
	(*UpdateUsernameRequest)(nil),           // 24: auth.UpdateUsernameRequest
	(*UpdateUsernameResponse)(nil),          // 25: auth.UpdateUsernameResponse
	(*CheckPasswordRequest)(nil),            // 26: auth.CheckPasswordRequest
	(*CheckPasswordResponse)(nil),           // 27: auth.CheckPasswordResponse
	(*UpdateEmailRequest)(nil),              // 28: auth.UpdateEmailRequest
	(*UpdateEmailResponse)(nil),             // 29: auth.UpdateEmailResponse
	(*VerifyNewEmailCodeRequest)(nil),       // 30: auth.VerifyNewEmailCodeRequest
	(*VerifyNewEmailCodeResponse)(nil),      // 31: auth.VerifyNewEmailCodeResponse
	(*UpdateAvatarRequest)(nil),             // 32: auth.UpdateAvatarRequest
	(*UpdateAvatarResponse)(nil),            // 33: auth.UpdateAvatarResponse
	(*StartPasswordResetRequest)(nil),       // 34: auth.StartPasswordResetRequest
	(*StartPasswordResetResponse)(nil),      // 35: auth.StartPasswordResetResponse
	(*VerifyPasswordResetCodeRequest)(nil),  // 36: auth.VerifyPasswordResetCodeRequest
	(*VerifyPasswordResetCodeResponse)(nil), // 37: auth.VerifyPasswordResetCodeResponse
	(*SetNewPasswordRequest)(nil),           // 38: auth.SetNewPasswordRequest
	(*SetNewPasswordResponse)(nil),          // 39: auth.SetNewPasswordResponse
	(*DeleteAvatarRequest)(nil),             // 40: auth.DeleteAvatarRequest
	(*DeleteAvatarResponse)(nil),            // 41: auth.DeleteAvatarResponse
	(*UserAddedMemoryRequest)(nil),          // 42: auth.UserAddedMemoryRequest
	(*UserAddedMemoryResponse)(nil),         // 43: auth.UserAddedMemoryResponse
	(*UserInvitedMemberRequest)(nil),        // 44: auth.UserInvitedMemberRequest
	(*UserInvitedMemberResponse)(nil),       // 45: auth.UserInvitedMemberResponse
	(*UserViewedMemoriesRequest)(nil),       // 46: auth.UserViewedMemoriesRequest
	(*UserViewedMemoriesResponse)(nil),      // 47: auth.UserViewedMemoriesResponse
	(*GetUserAchievementsRequest)(nil),      // 48: auth.GetUserAchievementsRequest
	(*GetUserAchievementsResponse)(nil),     // 49: auth.GetUserAchievementsResponse
	(*timestamppb.Timestamp)(nil),           // 50: google.protobuf.Timestamp
}
var file_proto_clients_auth_proto_depIdxs = []int32{
	50, // 0: auth.User.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: auth.GetUsersByIDsResponse.users:type_name -> auth.User
	0,  // 2: auth.GetUserByIDResponse.user:type_name -> auth.User
	1,  // 3: auth.GetUserAchievementsResponse.achievements:type_name -> auth.UserAchievement
	2,  // 4: auth.AuthService.StartRegistration:input_type -> auth.StartRegistrationRequest
	4,  // 5: auth.AuthService.VerifyEmailCode:input_type -> auth.VerifyEmailCodeRequest
	6,  // 6: auth.AuthService.SetPasswordAndUsername:input_type -> auth.SetPasswordAndUsernameRequest
	8,  // 7: auth.AuthService.Login:input_type -> auth.LoginRequest
	10, // 8: auth.AuthService.RefreshToken:input_type -> auth.RefreshTokenRequest
	12, // 9: auth.AuthService.ForgotPassword:input_type -> auth.ForgotPasswordRequest
	14, // 10: auth.AuthService.ResetPassword:input_type -> auth.ResetPasswordRequest
	16, // 11: auth.AuthService.Logout:input_type -> auth.LogoutRequest
	18, // 12: auth.AuthService.DeleteUser:input_type -> auth.DeleteUserRequest
	20, // 13: auth.AuthService.GetUsersByIDs:input_type -> auth.GetUsersByIDsRequest
	22, // 14: auth.AuthService.GetUserByID:input_type -> auth.GetUserByIDRequest
	24, // 15: auth.AuthService.UpdateUsername:input_type -> auth.UpdateUsernameRequest
	26, // 16: auth.AuthService.CheckPassword:input_type -> auth.CheckPasswordRequest
	28, // 17: auth.AuthService.UpdateEmail:input_type -> auth.UpdateEmailRequest
	30, // 18: auth.AuthService.VerifyNewEmailCode:input_type -> auth.VerifyNewEmailCodeRequest
	32, // 19: auth.AuthService.UpdateAvatar:input_type -> auth.UpdateAvatarRequest
	34, // 20: auth.AuthService.StartPasswordReset:input_type -> auth.StartPasswordResetRequest
	36, // 21: auth.AuthService.VerifyPasswordResetCode:input_type -> auth.VerifyPasswordResetCodeRequest
	38, // 22: auth.AuthService.SetNewPassword:input_type -> auth.SetNewPasswordRequest
	40, // 23: auth.AuthService.DeleteAvatar:input_type -> auth.DeleteAvatarRequest
	42, // 24: auth.AuthService.UserAddedMemory:input_type -> auth.UserAddedMemoryRequest
	44, // 25: auth.AuthService.UserInvitedMember:input_type -> auth.UserInvitedMemberRequest
	46, // 26: auth.AuthService.UserViewedMemories:input_type -> auth.UserViewedMemoriesRequest
	48, // 27: auth.AuthService.GetUserAchievements:input_type -> auth.GetUserAchievementsRequest
	3,  // 28: auth.AuthService.StartRegistration:output_type -> auth.StartRegistrationResponse
	5,  // 29: auth.AuthService.VerifyEmailCode:output_type -> auth.VerifyEmailCodeResponse
	7,  // 30: auth.AuthService.SetPasswordAndUsername:output_type -> auth.SetPasswordAndUsernameResponse
	9,  // 31: auth.AuthService.Login:output_type -> auth.LoginResponse
	11, // 32: auth.AuthService.RefreshToken:output_type -> auth.RefreshTokenResponse
	13, // 33: auth.AuthService.ForgotPassword:output_type -> auth.ForgotPasswordResponse
	15, // 34: auth.AuthService.ResetPassword:output_type -> auth.ResetPasswordResponse
	17, // 35: auth.AuthService.Logout:output_type -> auth.LogoutResponse
	19, // 36: auth.AuthService.DeleteUser:output_type -> auth.DeleteUserResponse
	21, // 37: auth.AuthService.GetUsersByIDs:output_type -> auth.GetUsersByIDsResponse
	23, // 38: auth.AuthService.GetUserByID:output_type -> auth.GetUserByIDResponse
	25, // 39: auth.AuthService.UpdateUsername:output_type -> auth.UpdateUsernameResponse
	27, // 40: auth.AuthService.CheckPassword:output_type -> auth.CheckPasswordResponse
	29, // 41: auth.AuthService.UpdateEmail:output_type -> auth.UpdateEmailResponse
	31, // 42: auth.AuthService.VerifyNewEmailCode:output_type -> auth.VerifyNewEmailCodeResponse
	33, // 43: auth.AuthService.UpdateAvatar:output_type -> auth.UpdateAvatarResponse
	35, // 44: auth.AuthService.StartPasswordReset:output_type -> auth.StartPasswordResetResponse
	37, // 45: auth.AuthService.VerifyPasswordResetCode:output_type -> auth.VerifyPasswordResetCodeResponse
	39, // 46: auth.AuthService.SetNewPassword:output_type -> auth.SetNewPasswordResponse
	41, // 47: auth.AuthService.DeleteAvatar:output_type -> auth.DeleteAvatarResponse
	43, // 48: auth.AuthService.UserAddedMemory:output_type -> auth.UserAddedMemoryResponse
	45, // 49: auth.AuthService.UserInvitedMember:output_type -> auth.UserInvitedMemberResponse
	47, // 50: auth.AuthService.UserViewedMemories:output_type -> auth.UserViewedMemoriesResponse
	49, // 51: auth.AuthService.GetUserAchievements:output_type -> auth.GetUserAchievementsResponse
	28, // [28:52] is the sub-list for method output_type
	4,  // [4:28] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_clients_auth_proto_init() }
func file_proto_clients_auth_proto_init() {
	if File_proto_clients_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_clients_auth_proto_rawDesc), len(file_proto_clients_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   50,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_clients_auth_proto_goTypes,
		DependencyIndexes: file_proto_clients_auth_proto_depIdxs,
		MessageInfos:      file_proto_clients_auth_proto_msgTypes,
	}.Build()
	File_proto_clients_auth_proto = out.File
	file_proto_clients_auth_proto_goTypes = nil
	file_proto_clients_auth_proto_depIdxs = nil
}
