// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/group.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GroupMessage представляет структуру группы
type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`                                   // URL изображения аватара
	AdminUserId   uint64                 `protobuf:"varint,4,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"` // ID пользователя-администратора (из Auth-Service)
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_proto_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Group) GetAdminUserId() uint64 {
	if x != nil {
		return x.AdminUserId
	}
	return 0
}

func (x *Group) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Group) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// GroupMemberMessage представляет структуру участника группы
type GroupMember struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId             uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId              uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // ID пользователя (из Auth-Service)
	IsAdmin             bool                   `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	MemoriesAddedCount  uint64                 `protobuf:"varint,5,opt,name=memories_added_count,json=memoriesAddedCount,proto3" json:"memories_added_count,omitempty"`    // Счетчики активности участника в группе
	MemoriesViewedCount uint64                 `protobuf:"varint,6,opt,name=memories_viewed_count,json=memoriesViewedCount,proto3" json:"memories_viewed_count,omitempty"` // Счетчики активности участника в группе
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // deleted_at не включаем
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_proto_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{1}
}

func (x *GroupMember) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupMember) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMember) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupMember) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *GroupMember) GetMemoriesAddedCount() uint64 {
	if x != nil {
		return x.MemoriesAddedCount
	}
	return 0
}

func (x *GroupMember) GetMemoriesViewedCount() uint64 {
	if x != nil {
		return x.MemoriesViewedCount
	}
	return 0
}

func (x *GroupMember) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GroupMember) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// GroupInvitationMessage представляет структуру приглашения в группу
type GroupInvitation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId         uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	InvitationCode  string                 `protobuf:"bytes,3,opt,name=invitation_code,json=invitationCode,proto3" json:"invitation_code,omitempty"`
	CreatedByUserId uint64                 `protobuf:"varint,4,opt,name=created_by_user_id,json=createdByUserId,proto3" json:"created_by_user_id,omitempty"` // ID пользователя, создавшего приглашение
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GroupInvitation) Reset() {
	*x = GroupInvitation{}
	mi := &file_proto_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInvitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInvitation) ProtoMessage() {}

func (x *GroupInvitation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInvitation.ProtoReflect.Descriptor instead.
func (*GroupInvitation) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{2}
}

func (x *GroupInvitation) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupInvitation) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupInvitation) GetInvitationCode() string {
	if x != nil {
		return x.InvitationCode
	}
	return ""
}

func (x *GroupInvitation) GetCreatedByUserId() uint64 {
	if x != nil {
		return x.CreatedByUserId
	}
	return 0
}

func (x *GroupInvitation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GroupInvitation) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// Запрос на создание группы
type CreateGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID пользователя, который создает группу (будет администратором) - приходит от API Gateway
	RequestingUserId uint64 `protobuf:"varint,1,opt,name=requesting_user_id,json=requestingUserId,proto3" json:"requesting_user_id,omitempty"`
	Name             string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_proto_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGroupRequest) GetRequestingUserId() uint64 {
	if x != nil {
		return x.RequestingUserId
	}
	return 0
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Ответ на создание группы
type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_proto_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{4}
}

func (x *CreateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

// Запрос на получение группы по ID
type GetGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID пользователя, запрашивающего информацию (для проверки прав доступа)
	RequestingUserId uint64 `protobuf:"varint,1,opt,name=requesting_user_id,json=requestingUserId,proto3" json:"requesting_user_id,omitempty"`
	GroupId          uint64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_proto_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{5}
}

func (x *GetGroupRequest) GetRequestingUserId() uint64 {
	if x != nil {
		return x.RequestingUserId
	}
	return 0
}

func (x *GetGroupRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// Ответ на получение группы
type GetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,2,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_proto_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{6}
}

func (x *GetGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GetGroupResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

// Запрос на обновление группы
type UpdateGroupRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestingUserId uint64                 `protobuf:"varint,1,opt,name=requesting_user_id,json=requestingUserId,proto3" json:"requesting_user_id,omitempty"` // ID пользователя, обновляющего группу (для проверки прав - только админ)
	GroupId          uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Используем обертку для необязательных полей, чтобы различать отсутствие значения и пустое значение
	Name          *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Image         []byte  `protobuf:"bytes,4,opt,name=image,proto3,oneof" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_proto_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateGroupRequest) GetRequestingUserId() uint64 {
	if x != nil {
		return x.RequestingUserId
	}
	return 0
}

func (x *UpdateGroupRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

// Ответ на обновление группы
type UpdateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupResponse) Reset() {
	*x = UpdateGroupResponse{}
	mi := &file_proto_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupResponse) ProtoMessage() {}

func (x *UpdateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

// Запрос на удаление группы
type DeleteGroupRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestingUserId uint64                 `protobuf:"varint,1,opt,name=requesting_user_id,json=requestingUserId,proto3" json:"requesting_user_id,omitempty"` // ID пользователя, удаляющего группу (только админ)
	GroupId          uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_proto_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteGroupRequest) GetRequestingUserId() uint64 {
	if x != nil {
		return x.RequestingUserId
	}
	return 0
}

func (x *DeleteGroupRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// Ответ на удаление группы
type DeleteGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupResponse) Reset() {
	*x = DeleteGroupResponse{}
	mi := &file_proto_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupResponse) ProtoMessage() {}

func (x *DeleteGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос на получение списка участников группы
type ListGroupMembersRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestingUserId uint64                 `protobuf:"varint,1,opt,name=requesting_user_id,json=requestingUserId,proto3" json:"requesting_user_id,omitempty"` // ID пользователя, запрашивающего список (для проверки прав - только участник)
	GroupId          uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListGroupMembersRequest) Reset() {
	*x = ListGroupMembersRequest{}
	mi := &file_proto_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersRequest) ProtoMessage() {}

func (x *ListGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMembersRequest.ProtoReflect.Descriptor instead.
func (*ListGroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{11}
}

func (x *ListGroupMembersRequest) GetRequestingUserId() uint64 {
	if x != nil {
		return x.RequestingUserId
	}
	return 0
}

func (x *ListGroupMembersRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// Ответ на получение списка участников группы
type ListGroupMembersResponse struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Members       []*ListGroupMembersResponse_MemberDetails `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMembersResponse) Reset() {
	*x = ListGroupMembersResponse{}
	mi := &file_proto_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersResponse) ProtoMessage() {}

func (x *ListGroupMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMembersResponse.ProtoReflect.Descriptor instead.
func (*ListGroupMembersResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{12}
}

func (x *ListGroupMembersResponse) GetMembers() []*ListGroupMembersResponse_MemberDetails {
	if x != nil {
		return x.Members
	}
	return nil
}

// Запрос на удаление участника из группы (админом или сам участник)
type RemoveGroupMemberRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestingUserId uint64                 `protobuf:"varint,1,opt,name=requesting_user_id,json=requestingUserId,proto3" json:"requesting_user_id,omitempty"` // ID пользователя, выполняющего удаление (админ или сам удаляемый)
	GroupId          uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserIdToRemove   uint64                 `protobuf:"varint,3,opt,name=user_id_to_remove,json=userIdToRemove,proto3" json:"user_id_to_remove,omitempty"` // ID пользователя, которого удаляют
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RemoveGroupMemberRequest) Reset() {
	*x = RemoveGroupMemberRequest{}
	mi := &file_proto_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGroupMemberRequest) ProtoMessage() {}

func (x *RemoveGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveGroupMemberRequest) GetRequestingUserId() uint64 {
	if x != nil {
		return x.RequestingUserId
	}
	return 0
}

func (x *RemoveGroupMemberRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RemoveGroupMemberRequest) GetUserIdToRemove() uint64 {
	if x != nil {
		return x.UserIdToRemove
	}
	return 0
}

// Ответ на удаление участника
type RemoveGroupMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveGroupMemberResponse) Reset() {
	*x = RemoveGroupMemberResponse{}
	mi := &file_proto_group_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGroupMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGroupMemberResponse) ProtoMessage() {}

func (x *RemoveGroupMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGroupMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveGroupMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveGroupMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckUserInGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserInGroupRequest) Reset() {
	*x = CheckUserInGroupRequest{}
	mi := &file_proto_group_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserInGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserInGroupRequest) ProtoMessage() {}

func (x *CheckUserInGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserInGroupRequest.ProtoReflect.Descriptor instead.
func (*CheckUserInGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{15}
}

func (x *CheckUserInGroupRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckUserInGroupRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type CheckUserInGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsInGroup     bool                   `protobuf:"varint,1,opt,name=is_in_group,json=isInGroup,proto3" json:"is_in_group,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,2,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserInGroupResponse) Reset() {
	*x = CheckUserInGroupResponse{}
	mi := &file_proto_group_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserInGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserInGroupResponse) ProtoMessage() {}

func (x *CheckUserInGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserInGroupResponse.ProtoReflect.Descriptor instead.
func (*CheckUserInGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{16}
}

func (x *CheckUserInGroupResponse) GetIsInGroup() bool {
	if x != nil {
		return x.IsInGroup
	}
	return false
}

func (x *CheckUserInGroupResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

// Запрос на создание приглашения в группу
type CreateGroupInvitationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestingUserId uint64                 `protobuf:"varint,1,opt,name=requesting_user_id,json=requestingUserId,proto3" json:"requesting_user_id,omitempty"` // ID пользователя, создающего приглашение (только админ)
	GroupId          uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Можно добавить срок действия для приглашения
	Duration      *durationpb.Duration `protobuf:"bytes,3,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupInvitationRequest) Reset() {
	*x = CreateGroupInvitationRequest{}
	mi := &file_proto_group_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupInvitationRequest) ProtoMessage() {}

func (x *CreateGroupInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupInvitationRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupInvitationRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{17}
}

func (x *CreateGroupInvitationRequest) GetRequestingUserId() uint64 {
	if x != nil {
		return x.RequestingUserId
	}
	return 0
}

func (x *CreateGroupInvitationRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateGroupInvitationRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

// Ответ на создание приглашения
type CreateGroupInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitation    *GroupInvitation       `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupInvitationResponse) Reset() {
	*x = CreateGroupInvitationResponse{}
	mi := &file_proto_group_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupInvitationResponse) ProtoMessage() {}

func (x *CreateGroupInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupInvitationResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupInvitationResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{18}
}

func (x *CreateGroupInvitationResponse) GetInvitation() *GroupInvitation {
	if x != nil {
		return x.Invitation
	}
	return nil
}

// Запрос на принятие приглашения
type AcceptGroupInvitationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestingUserId uint64                 `protobuf:"varint,1,opt,name=requesting_user_id,json=requestingUserId,proto3" json:"requesting_user_id,omitempty"` // ID пользователя, принимающего приглашение
	InvitationCode   string                 `protobuf:"bytes,2,opt,name=invitation_code,json=invitationCode,proto3" json:"invitation_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AcceptGroupInvitationRequest) Reset() {
	*x = AcceptGroupInvitationRequest{}
	mi := &file_proto_group_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptGroupInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptGroupInvitationRequest) ProtoMessage() {}

func (x *AcceptGroupInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptGroupInvitationRequest.ProtoReflect.Descriptor instead.
func (*AcceptGroupInvitationRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{19}
}

func (x *AcceptGroupInvitationRequest) GetRequestingUserId() uint64 {
	if x != nil {
		return x.RequestingUserId
	}
	return 0
}

func (x *AcceptGroupInvitationRequest) GetInvitationCode() string {
	if x != nil {
		return x.InvitationCode
	}
	return ""
}

// Ответ на принятие приглашения
type AcceptGroupInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupMember   *GroupMember           `protobuf:"bytes,1,opt,name=group_member,json=groupMember,proto3" json:"group_member,omitempty"`          // Информация о только что созданном участии
	Group         *Group                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`                                         // Возможно, вернуть информацию о группе, к которой присоединился
	InviterUserId uint64                 `protobuf:"varint,3,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"` // ID пользователя, который создал приглашение
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptGroupInvitationResponse) Reset() {
	*x = AcceptGroupInvitationResponse{}
	mi := &file_proto_group_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptGroupInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptGroupInvitationResponse) ProtoMessage() {}

func (x *AcceptGroupInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptGroupInvitationResponse.ProtoReflect.Descriptor instead.
func (*AcceptGroupInvitationResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{20}
}

func (x *AcceptGroupInvitationResponse) GetGroupMember() *GroupMember {
	if x != nil {
		return x.GroupMember
	}
	return nil
}

func (x *AcceptGroupInvitationResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *AcceptGroupInvitationResponse) GetInviterUserId() uint64 {
	if x != nil {
		return x.InviterUserId
	}
	return 0
}

// Запрос на получение списка групп пользователя
// Этот метод специально для списка "Мои группы" пользователя.
type ListUserGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // ID пользователя, чьи группы запрашиваем
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserGroupsRequest) Reset() {
	*x = ListUserGroupsRequest{}
	mi := &file_proto_group_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserGroupsRequest) ProtoMessage() {}

func (x *ListUserGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListUserGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{21}
}

func (x *ListUserGroupsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Ответ на получение списка групп пользователя
type ListUserGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserGroupsResponse) Reset() {
	*x = ListUserGroupsResponse{}
	mi := &file_proto_group_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserGroupsResponse) ProtoMessage() {}

func (x *ListUserGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListUserGroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{22}
}

func (x *ListUserGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type DeleteGroupAvatarRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestingUserId uint64                 `protobuf:"varint,1,opt,name=requesting_user_id,json=requestingUserId,proto3" json:"requesting_user_id,omitempty"` // ID пользователя, обновляющего группу
	GroupId          uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteGroupAvatarRequest) Reset() {
	*x = DeleteGroupAvatarRequest{}
	mi := &file_proto_group_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupAvatarRequest) ProtoMessage() {}

func (x *DeleteGroupAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupAvatarRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupAvatarRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteGroupAvatarRequest) GetRequestingUserId() uint64 {
	if x != nil {
		return x.RequestingUserId
	}
	return 0
}

func (x *DeleteGroupAvatarRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type DeleteGroupAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupAvatarResponse) Reset() {
	*x = DeleteGroupAvatarResponse{}
	mi := &file_proto_group_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupAvatarResponse) ProtoMessage() {}

func (x *DeleteGroupAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupAvatarResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupAvatarResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteGroupAvatarResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GroupMemberAddedMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberAddedMemoryRequest) Reset() {
	*x = GroupMemberAddedMemoryRequest{}
	mi := &file_proto_group_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberAddedMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberAddedMemoryRequest) ProtoMessage() {}

func (x *GroupMemberAddedMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberAddedMemoryRequest.ProtoReflect.Descriptor instead.
func (*GroupMemberAddedMemoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{25}
}

func (x *GroupMemberAddedMemoryRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMemberAddedMemoryRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GroupMemberAddedMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberAddedMemoryResponse) Reset() {
	*x = GroupMemberAddedMemoryResponse{}
	mi := &file_proto_group_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberAddedMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberAddedMemoryResponse) ProtoMessage() {}

func (x *GroupMemberAddedMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberAddedMemoryResponse.ProtoReflect.Descriptor instead.
func (*GroupMemberAddedMemoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{26}
}

func (x *GroupMemberAddedMemoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GroupMemberViewedMemoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberViewedMemoriesRequest) Reset() {
	*x = GroupMemberViewedMemoriesRequest{}
	mi := &file_proto_group_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberViewedMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberViewedMemoriesRequest) ProtoMessage() {}

func (x *GroupMemberViewedMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberViewedMemoriesRequest.ProtoReflect.Descriptor instead.
func (*GroupMemberViewedMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{27}
}

func (x *GroupMemberViewedMemoriesRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMemberViewedMemoriesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupMemberViewedMemoriesRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GroupMemberViewedMemoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberViewedMemoriesResponse) Reset() {
	*x = GroupMemberViewedMemoriesResponse{}
	mi := &file_proto_group_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberViewedMemoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberViewedMemoriesResponse) ProtoMessage() {}

func (x *GroupMemberViewedMemoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberViewedMemoriesResponse.ProtoReflect.Descriptor instead.
func (*GroupMemberViewedMemoriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{28}
}

func (x *GroupMemberViewedMemoriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Тут нужно возвращать не только GroupMember, но и информацию о пользователе (username, image и т.д.)
// Так как информация о пользователе в Auth-Service, group-service придется запрашивать ее у Auth-Service.
// Для gRPC сообщения можно создать отдельную структуру, объединяющую GroupMember и User info.
type ListGroupMembersResponse_MemberDetails struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username            string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                                                     // Из Auth-Service
	UserImage           string                 `protobuf:"bytes,3,opt,name=user_image,json=userImage,proto3" json:"user_image,omitempty"`                                  // Из Auth-Service
	IsAdmin             bool                   `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`                                       // Из GroupMember
	MemoriesAddedCount  uint64                 `protobuf:"varint,5,opt,name=memories_added_count,json=memoriesAddedCount,proto3" json:"memories_added_count,omitempty"`    // Из GroupMember
	MemoriesViewedCount uint64                 `protobuf:"varint,6,opt,name=memories_viewed_count,json=memoriesViewedCount,proto3" json:"memories_viewed_count,omitempty"` // Из GroupMember
	JoinedAt            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`                                     // group_members.created_at
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListGroupMembersResponse_MemberDetails) Reset() {
	*x = ListGroupMembersResponse_MemberDetails{}
	mi := &file_proto_group_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMembersResponse_MemberDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersResponse_MemberDetails) ProtoMessage() {}

func (x *ListGroupMembersResponse_MemberDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMembersResponse_MemberDetails.ProtoReflect.Descriptor instead.
func (*ListGroupMembersResponse_MemberDetails) Descriptor() ([]byte, []int) {
	return file_proto_group_proto_rawDescGZIP(), []int{12, 0}
}

func (x *ListGroupMembersResponse_MemberDetails) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListGroupMembersResponse_MemberDetails) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ListGroupMembersResponse_MemberDetails) GetUserImage() string {
	if x != nil {
		return x.UserImage
	}
	return ""
}

func (x *ListGroupMembersResponse_MemberDetails) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *ListGroupMembersResponse_MemberDetails) GetMemoriesAddedCount() uint64 {
	if x != nil {
		return x.MemoriesAddedCount
	}
	return 0
}

func (x *ListGroupMembersResponse_MemberDetails) GetMemoriesViewedCount() uint64 {
	if x != nil {
		return x.MemoriesViewedCount
	}
	return 0
}

func (x *ListGroupMembersResponse_MemberDetails) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

var File_proto_group_proto protoreflect.FileDescriptor

const file_proto_group_proto_rawDesc = "" +
	"\n" +
	"\x11proto/group.proto\x12\x05group\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xdb\x01\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\"\n" +
	"\radmin_user_id\x18\x04 \x01(\x04R\vadminUserId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc8\x02\n" +
	"\vGroupMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x19\n" +
	"\bis_admin\x18\x04 \x01(\bR\aisAdmin\x120\n" +
	"\x14memories_added_count\x18\x05 \x01(\x04R\x12memoriesAddedCount\x122\n" +
	"\x15memories_viewed_count\x18\x06 \x01(\x04R\x13memoriesViewedCount\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x88\x02\n" +
	"\x0fGroupInvitation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12'\n" +
	"\x0finvitation_code\x18\x03 \x01(\tR\x0einvitationCode\x12+\n" +
	"\x12created_by_user_id\x18\x04 \x01(\x04R\x0fcreatedByUserId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"V\n" +
	"\x12CreateGroupRequest\x12,\n" +
	"\x12requesting_user_id\x18\x01 \x01(\x04R\x10requestingUserId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"9\n" +
	"\x13CreateGroupResponse\x12\"\n" +
	"\x05group\x18\x01 \x01(\v2\f.group.GroupR\x05group\"Z\n" +
	"\x0fGetGroupRequest\x12,\n" +
	"\x12requesting_user_id\x18\x01 \x01(\x04R\x10requestingUserId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\"Q\n" +
	"\x10GetGroupResponse\x12\"\n" +
	"\x05group\x18\x01 \x01(\v2\f.group.GroupR\x05group\x12\x19\n" +
	"\bis_admin\x18\x02 \x01(\bR\aisAdmin\"\xa4\x01\n" +
	"\x12UpdateGroupRequest\x12,\n" +
	"\x12requesting_user_id\x18\x01 \x01(\x04R\x10requestingUserId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05image\x18\x04 \x01(\fH\x01R\x05image\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_image\"9\n" +
	"\x13UpdateGroupResponse\x12\"\n" +
	"\x05group\x18\x01 \x01(\v2\f.group.GroupR\x05group\"]\n" +
	"\x12DeleteGroupRequest\x12,\n" +
	"\x12requesting_user_id\x18\x01 \x01(\x04R\x10requestingUserId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\"/\n" +
	"\x13DeleteGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"b\n" +
	"\x17ListGroupMembersRequest\x12,\n" +
	"\x12requesting_user_id\x18\x01 \x01(\x04R\x10requestingUserId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\"\x83\x03\n" +
	"\x18ListGroupMembersResponse\x12G\n" +
	"\amembers\x18\x01 \x03(\v2-.group.ListGroupMembersResponse.MemberDetailsR\amembers\x1a\x9d\x02\n" +
	"\rMemberDetails\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"user_image\x18\x03 \x01(\tR\tuserImage\x12\x19\n" +
	"\bis_admin\x18\x04 \x01(\bR\aisAdmin\x120\n" +
	"\x14memories_added_count\x18\x05 \x01(\x04R\x12memoriesAddedCount\x122\n" +
	"\x15memories_viewed_count\x18\x06 \x01(\x04R\x13memoriesViewedCount\x127\n" +
	"\tjoined_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"\x8e\x01\n" +
	"\x18RemoveGroupMemberRequest\x12,\n" +
	"\x12requesting_user_id\x18\x01 \x01(\x04R\x10requestingUserId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12)\n" +
	"\x11user_id_to_remove\x18\x03 \x01(\x04R\x0euserIdToRemove\"5\n" +
	"\x19RemoveGroupMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"M\n" +
	"\x17CheckUserInGroupRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\"U\n" +
	"\x18CheckUserInGroupResponse\x12\x1e\n" +
	"\vis_in_group\x18\x01 \x01(\bR\tisInGroup\x12\x19\n" +
	"\bis_admin\x18\x02 \x01(\bR\aisAdmin\"\xb0\x01\n" +
	"\x1cCreateGroupInvitationRequest\x12,\n" +
	"\x12requesting_user_id\x18\x01 \x01(\x04R\x10requestingUserId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12:\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationH\x00R\bduration\x88\x01\x01B\v\n" +
	"\t_duration\"W\n" +
	"\x1dCreateGroupInvitationResponse\x126\n" +
	"\n" +
	"invitation\x18\x01 \x01(\v2\x16.group.GroupInvitationR\n" +
	"invitation\"u\n" +
	"\x1cAcceptGroupInvitationRequest\x12,\n" +
	"\x12requesting_user_id\x18\x01 \x01(\x04R\x10requestingUserId\x12'\n" +
	"\x0finvitation_code\x18\x02 \x01(\tR\x0einvitationCode\"\xa2\x01\n" +
	"\x1dAcceptGroupInvitationResponse\x125\n" +
	"\fgroup_member\x18\x01 \x01(\v2\x12.group.GroupMemberR\vgroupMember\x12\"\n" +
	"\x05group\x18\x02 \x01(\v2\f.group.GroupR\x05group\x12&\n" +
	"\x0finviter_user_id\x18\x03 \x01(\x04R\rinviterUserId\"0\n" +
	"\x15ListUserGroupsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\">\n" +
	"\x16ListUserGroupsResponse\x12$\n" +
	"\x06groups\x18\x01 \x03(\v2\f.group.GroupR\x06groups\"c\n" +
	"\x18DeleteGroupAvatarRequest\x12,\n" +
	"\x12requesting_user_id\x18\x01 \x01(\x04R\x10requestingUserId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\"5\n" +
	"\x19DeleteGroupAvatarResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"S\n" +
	"\x1dGroupMemberAddedMemoryRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\":\n" +
	"\x1eGroupMemberAddedMemoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"l\n" +
	" GroupMemberViewedMemoriesRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\"=\n" +
	"!GroupMemberViewedMemoriesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe5\b\n" +
	"\fGroupService\x12D\n" +
	"\vCreateGroup\x12\x19.group.CreateGroupRequest\x1a\x1a.group.CreateGroupResponse\x12;\n" +
	"\bGetGroup\x12\x16.group.GetGroupRequest\x1a\x17.group.GetGroupResponse\x12D\n" +
	"\vUpdateGroup\x12\x19.group.UpdateGroupRequest\x1a\x1a.group.UpdateGroupResponse\x12D\n" +
	"\vDeleteGroup\x12\x19.group.DeleteGroupRequest\x1a\x1a.group.DeleteGroupResponse\x12V\n" +
	"\x11DeleteGroupAvatar\x12\x1f.group.DeleteGroupAvatarRequest\x1a .group.DeleteGroupAvatarResponse\x12S\n" +
	"\x10ListGroupMembers\x12\x1e.group.ListGroupMembersRequest\x1a\x1f.group.ListGroupMembersResponse\x12V\n" +
	"\x11RemoveGroupMember\x12\x1f.group.RemoveGroupMemberRequest\x1a .group.RemoveGroupMemberResponse\x12S\n" +
	"\x10CheckUserInGroup\x12\x1e.group.CheckUserInGroupRequest\x1a\x1f.group.CheckUserInGroupResponse\x12b\n" +
	"\x15CreateGroupInvitation\x12#.group.CreateGroupInvitationRequest\x1a$.group.CreateGroupInvitationResponse\x12b\n" +
	"\x15AcceptGroupInvitation\x12#.group.AcceptGroupInvitationRequest\x1a$.group.AcceptGroupInvitationResponse\x12M\n" +
	"\x0eListUserGroups\x12\x1c.group.ListUserGroupsRequest\x1a\x1d.group.ListUserGroupsResponse\x12e\n" +
	"\x16GroupMemberAddedMemory\x12$.group.GroupMemberAddedMemoryRequest\x1a%.group.GroupMemberAddedMemoryResponse\x12n\n" +
	"\x19GroupMemberViewedMemories\x12'.group.GroupMemberViewedMemoriesRequest\x1a(.group.GroupMemberViewedMemoriesResponseB(Z&Rewind-2.0/Backend/group-service/protob\x06proto3"

var (
	file_proto_group_proto_rawDescOnce sync.Once
	file_proto_group_proto_rawDescData []byte
)

func file_proto_group_proto_rawDescGZIP() []byte {
	file_proto_group_proto_rawDescOnce.Do(func() {
		file_proto_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_group_proto_rawDesc), len(file_proto_group_proto_rawDesc)))
	})
	return file_proto_group_proto_rawDescData
}

var file_proto_group_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_proto_group_proto_goTypes = []any{
	(*Group)(nil),                                  // 0: group.Group
	(*GroupMember)(nil),                            // 1: group.GroupMember
	(*GroupInvitation)(nil),                        // 2: group.GroupInvitation
	(*CreateGroupRequest)(nil),                     // 3: group.CreateGroupRequest
	(*CreateGroupResponse)(nil),                    // 4: group.CreateGroupResponse
	(*GetGroupRequest)(nil),                        // 5: group.GetGroupRequest
	(*GetGroupResponse)(nil),                       // 6: group.GetGroupResponse
	(*UpdateGroupRequest)(nil),                     // 7: group.UpdateGroupRequest
	(*UpdateGroupResponse)(nil),                    // 8: group.UpdateGroupResponse
	(*DeleteGroupRequest)(nil),                     // 9: group.DeleteGroupRequest
	(*DeleteGroupResponse)(nil),                    // 10: group.DeleteGroupResponse
	(*ListGroupMembersRequest)(nil),                // 11: group.ListGroupMembersRequest
	(*ListGroupMembersResponse)(nil),               // 12: group.ListGroupMembersResponse
	(*RemoveGroupMemberRequest)(nil),               // 13: group.RemoveGroupMemberRequest
	(*RemoveGroupMemberResponse)(nil),              // 14: group.RemoveGroupMemberResponse
	(*CheckUserInGroupRequest)(nil),                // 15: group.CheckUserInGroupRequest
	(*CheckUserInGroupResponse)(nil),               // 16: group.CheckUserInGroupResponse
	(*CreateGroupInvitationRequest)(nil),           // 17: group.CreateGroupInvitationRequest
	(*CreateGroupInvitationResponse)(nil),          // 18: group.CreateGroupInvitationResponse
	(*AcceptGroupInvitationRequest)(nil),           // 19: group.AcceptGroupInvitationRequest
	(*AcceptGroupInvitationResponse)(nil),          // 20: group.AcceptGroupInvitationResponse
	(*ListUserGroupsRequest)(nil),                  // 21: group.ListUserGroupsRequest
	(*ListUserGroupsResponse)(nil),                 // 22: group.ListUserGroupsResponse
	(*DeleteGroupAvatarRequest)(nil),               // 23: group.DeleteGroupAvatarRequest
	(*DeleteGroupAvatarResponse)(nil),              // 24: group.DeleteGroupAvatarResponse
	(*GroupMemberAddedMemoryRequest)(nil),          // 25: group.GroupMemberAddedMemoryRequest
	(*GroupMemberAddedMemoryResponse)(nil),         // 26: group.GroupMemberAddedMemoryResponse
	(*GroupMemberViewedMemoriesRequest)(nil),       // 27: group.GroupMemberViewedMemoriesRequest
	(*GroupMemberViewedMemoriesResponse)(nil),      // 28: group.GroupMemberViewedMemoriesResponse
	(*ListGroupMembersResponse_MemberDetails)(nil), // 29: group.ListGroupMembersResponse.MemberDetails
	(*timestamppb.Timestamp)(nil),                  // 30: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),                    // 31: google.protobuf.Duration
}
var file_proto_group_proto_depIdxs = []int32{
	30, // 0: group.Group.created_at:type_name -> google.protobuf.Timestamp
	30, // 1: group.Group.updated_at:type_name -> google.protobuf.Timestamp
	30, // 2: group.GroupMember.created_at:type_name -> google.protobuf.Timestamp
	30, // 3: group.GroupMember.updated_at:type_name -> google.protobuf.Timestamp
	30, // 4: group.GroupInvitation.created_at:type_name -> google.protobuf.Timestamp
	30, // 5: group.GroupInvitation.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 6: group.CreateGroupResponse.group:type_name -> group.Group
	0,  // 7: group.GetGroupResponse.group:type_name -> group.Group
	0,  // 8: group.UpdateGroupResponse.group:type_name -> group.Group
	29, // 9: group.ListGroupMembersResponse.members:type_name -> group.ListGroupMembersResponse.MemberDetails
	31, // 10: group.CreateGroupInvitationRequest.duration:type_name -> google.protobuf.Duration
	2,  // 11: group.CreateGroupInvitationResponse.invitation:type_name -> group.GroupInvitation
	1,  // 12: group.AcceptGroupInvitationResponse.group_member:type_name -> group.GroupMember
	0,  // 13: group.AcceptGroupInvitationResponse.group:type_name -> group.Group
	0,  // 14: group.ListUserGroupsResponse.groups:type_name -> group.Group
	30, // 15: group.ListGroupMembersResponse.MemberDetails.joined_at:type_name -> google.protobuf.Timestamp
	3,  // 16: group.GroupService.CreateGroup:input_type -> group.CreateGroupRequest
	5,  // 17: group.GroupService.GetGroup:input_type -> group.GetGroupRequest
	7,  // 18: group.GroupService.UpdateGroup:input_type -> group.UpdateGroupRequest
	9,  // 19: group.GroupService.DeleteGroup:input_type -> group.DeleteGroupRequest
	23, // 20: group.GroupService.DeleteGroupAvatar:input_type -> group.DeleteGroupAvatarRequest
	11, // 21: group.GroupService.ListGroupMembers:input_type -> group.ListGroupMembersRequest
	13, // 22: group.GroupService.RemoveGroupMember:input_type -> group.RemoveGroupMemberRequest
	15, // 23: group.GroupService.CheckUserInGroup:input_type -> group.CheckUserInGroupRequest
	17, // 24: group.GroupService.CreateGroupInvitation:input_type -> group.CreateGroupInvitationRequest
	19, // 25: group.GroupService.AcceptGroupInvitation:input_type -> group.AcceptGroupInvitationRequest
	21, // 26: group.GroupService.ListUserGroups:input_type -> group.ListUserGroupsRequest
	25, // 27: group.GroupService.GroupMemberAddedMemory:input_type -> group.GroupMemberAddedMemoryRequest
	27, // 28: group.GroupService.GroupMemberViewedMemories:input_type -> group.GroupMemberViewedMemoriesRequest
	4,  // 29: group.GroupService.CreateGroup:output_type -> group.CreateGroupResponse
	6,  // 30: group.GroupService.GetGroup:output_type -> group.GetGroupResponse
	8,  // 31: group.GroupService.UpdateGroup:output_type -> group.UpdateGroupResponse
	10, // 32: group.GroupService.DeleteGroup:output_type -> group.DeleteGroupResponse
	24, // 33: group.GroupService.DeleteGroupAvatar:output_type -> group.DeleteGroupAvatarResponse
	12, // 34: group.GroupService.ListGroupMembers:output_type -> group.ListGroupMembersResponse
	14, // 35: group.GroupService.RemoveGroupMember:output_type -> group.RemoveGroupMemberResponse
	16, // 36: group.GroupService.CheckUserInGroup:output_type -> group.CheckUserInGroupResponse
	18, // 37: group.GroupService.CreateGroupInvitation:output_type -> group.CreateGroupInvitationResponse
	20, // 38: group.GroupService.AcceptGroupInvitation:output_type -> group.AcceptGroupInvitationResponse
	22, // 39: group.GroupService.ListUserGroups:output_type -> group.ListUserGroupsResponse
	26, // 40: group.GroupService.GroupMemberAddedMemory:output_type -> group.GroupMemberAddedMemoryResponse
	28, // 41: group.GroupService.GroupMemberViewedMemories:output_type -> group.GroupMemberViewedMemoriesResponse
	29, // [29:42] is the sub-list for method output_type
	16, // [16:29] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_group_proto_init() }
func file_proto_group_proto_init() {
	if File_proto_group_proto != nil {
		return
	}
	file_proto_group_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_group_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_group_proto_rawDesc), len(file_proto_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_group_proto_goTypes,
		DependencyIndexes: file_proto_group_proto_depIdxs,
		MessageInfos:      file_proto_group_proto_msgTypes,
	}.Build()
	File_proto_group_proto = out.File
	file_proto_group_proto_goTypes = nil
	file_proto_group_proto_depIdxs = nil
}
