// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/memory.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemoryService_CreateMemory_FullMethodName                   = "/memory.MemoryService/CreateMemory"
	MemoryService_DeleteMemory_FullMethodName                   = "/memory.MemoryService/DeleteMemory"
	MemoryService_DeleteMemoriesByGroup_FullMethodName          = "/memory.MemoryService/DeleteMemoriesByGroup"
	MemoryService_ListMemoriesByGroup_FullMethodName            = "/memory.MemoryService/ListMemoriesByGroup"
	MemoryService_ListMemoriesByGroupWithFilters_FullMethodName = "/memory.MemoryService/ListMemoriesByGroupWithFilters"
	MemoryService_CreateMemoryTag_FullMethodName                = "/memory.MemoryService/CreateMemoryTag"
	MemoryService_DeleteMemoryTag_FullMethodName                = "/memory.MemoryService/DeleteMemoryTag"
	MemoryService_ListMemoryTagsByMemoryID_FullMethodName       = "/memory.MemoryService/ListMemoryTagsByMemoryID"
	MemoryService_CreateFavourite_FullMethodName                = "/memory.MemoryService/CreateFavourite"
	MemoryService_DeleteFavourite_FullMethodName                = "/memory.MemoryService/DeleteFavourite"
	MemoryService_DeleteFavouritesByUserID_FullMethodName       = "/memory.MemoryService/DeleteFavouritesByUserID"
)

// MemoryServiceClient is the client API for MemoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис для работы с воспоминаниями
type MemoryServiceClient interface {
	CreateMemory(ctx context.Context, in *CreateMemoryRequest, opts ...grpc.CallOption) (*CreateMemoryResponse, error)
	DeleteMemory(ctx context.Context, in *DeleteMemoryRequest, opts ...grpc.CallOption) (*DeleteMemoryResponse, error)
	DeleteMemoriesByGroup(ctx context.Context, in *DeleteMemoriesByGroupRequest, opts ...grpc.CallOption) (*DeleteMemoriesByGroupResponse, error)
	ListMemoriesByGroup(ctx context.Context, in *ListMemoriesByGroupRequest, opts ...grpc.CallOption) (*ListMemoriesByGroupResponse, error)
	ListMemoriesByGroupWithFilters(ctx context.Context, in *ListMemoriesByGroupWithFiltersRequest, opts ...grpc.CallOption) (*ListMemoriesByGroupWithFiltersResponse, error)
	CreateMemoryTag(ctx context.Context, in *CreateMemoryTagRequest, opts ...grpc.CallOption) (*CreateMemoryTagResponse, error)
	DeleteMemoryTag(ctx context.Context, in *DeleteMemoryTagRequest, opts ...grpc.CallOption) (*DeleteMemoryTagResponse, error)
	ListMemoryTagsByMemoryID(ctx context.Context, in *ListMemoryTagsByMemoryIDRequest, opts ...grpc.CallOption) (*ListMemoryTagsByMemoryIDResponse, error)
	CreateFavourite(ctx context.Context, in *CreateFavouriteRequest, opts ...grpc.CallOption) (*CreateFavouriteResponse, error)
	DeleteFavourite(ctx context.Context, in *DeleteFavouriteRequest, opts ...grpc.CallOption) (*DeleteFavouriteResponse, error)
	DeleteFavouritesByUserID(ctx context.Context, in *DeleteFavouritedByUserIDRequest, opts ...grpc.CallOption) (*DeleteFavouritedByUserIDResponse, error)
}

type memoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryServiceClient(cc grpc.ClientConnInterface) MemoryServiceClient {
	return &memoryServiceClient{cc}
}

func (c *memoryServiceClient) CreateMemory(ctx context.Context, in *CreateMemoryRequest, opts ...grpc.CallOption) (*CreateMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMemoryResponse)
	err := c.cc.Invoke(ctx, MemoryService_CreateMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) DeleteMemory(ctx context.Context, in *DeleteMemoryRequest, opts ...grpc.CallOption) (*DeleteMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMemoryResponse)
	err := c.cc.Invoke(ctx, MemoryService_DeleteMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) DeleteMemoriesByGroup(ctx context.Context, in *DeleteMemoriesByGroupRequest, opts ...grpc.CallOption) (*DeleteMemoriesByGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMemoriesByGroupResponse)
	err := c.cc.Invoke(ctx, MemoryService_DeleteMemoriesByGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) ListMemoriesByGroup(ctx context.Context, in *ListMemoriesByGroupRequest, opts ...grpc.CallOption) (*ListMemoriesByGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMemoriesByGroupResponse)
	err := c.cc.Invoke(ctx, MemoryService_ListMemoriesByGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) ListMemoriesByGroupWithFilters(ctx context.Context, in *ListMemoriesByGroupWithFiltersRequest, opts ...grpc.CallOption) (*ListMemoriesByGroupWithFiltersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMemoriesByGroupWithFiltersResponse)
	err := c.cc.Invoke(ctx, MemoryService_ListMemoriesByGroupWithFilters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) CreateMemoryTag(ctx context.Context, in *CreateMemoryTagRequest, opts ...grpc.CallOption) (*CreateMemoryTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMemoryTagResponse)
	err := c.cc.Invoke(ctx, MemoryService_CreateMemoryTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) DeleteMemoryTag(ctx context.Context, in *DeleteMemoryTagRequest, opts ...grpc.CallOption) (*DeleteMemoryTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMemoryTagResponse)
	err := c.cc.Invoke(ctx, MemoryService_DeleteMemoryTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) ListMemoryTagsByMemoryID(ctx context.Context, in *ListMemoryTagsByMemoryIDRequest, opts ...grpc.CallOption) (*ListMemoryTagsByMemoryIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMemoryTagsByMemoryIDResponse)
	err := c.cc.Invoke(ctx, MemoryService_ListMemoryTagsByMemoryID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) CreateFavourite(ctx context.Context, in *CreateFavouriteRequest, opts ...grpc.CallOption) (*CreateFavouriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFavouriteResponse)
	err := c.cc.Invoke(ctx, MemoryService_CreateFavourite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) DeleteFavourite(ctx context.Context, in *DeleteFavouriteRequest, opts ...grpc.CallOption) (*DeleteFavouriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFavouriteResponse)
	err := c.cc.Invoke(ctx, MemoryService_DeleteFavourite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) DeleteFavouritesByUserID(ctx context.Context, in *DeleteFavouritedByUserIDRequest, opts ...grpc.CallOption) (*DeleteFavouritedByUserIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFavouritedByUserIDResponse)
	err := c.cc.Invoke(ctx, MemoryService_DeleteFavouritesByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemoryServiceServer is the server API for MemoryService service.
// All implementations must embed UnimplementedMemoryServiceServer
// for forward compatibility.
//
// Сервис для работы с воспоминаниями
type MemoryServiceServer interface {
	CreateMemory(context.Context, *CreateMemoryRequest) (*CreateMemoryResponse, error)
	DeleteMemory(context.Context, *DeleteMemoryRequest) (*DeleteMemoryResponse, error)
	DeleteMemoriesByGroup(context.Context, *DeleteMemoriesByGroupRequest) (*DeleteMemoriesByGroupResponse, error)
	ListMemoriesByGroup(context.Context, *ListMemoriesByGroupRequest) (*ListMemoriesByGroupResponse, error)
	ListMemoriesByGroupWithFilters(context.Context, *ListMemoriesByGroupWithFiltersRequest) (*ListMemoriesByGroupWithFiltersResponse, error)
	CreateMemoryTag(context.Context, *CreateMemoryTagRequest) (*CreateMemoryTagResponse, error)
	DeleteMemoryTag(context.Context, *DeleteMemoryTagRequest) (*DeleteMemoryTagResponse, error)
	ListMemoryTagsByMemoryID(context.Context, *ListMemoryTagsByMemoryIDRequest) (*ListMemoryTagsByMemoryIDResponse, error)
	CreateFavourite(context.Context, *CreateFavouriteRequest) (*CreateFavouriteResponse, error)
	DeleteFavourite(context.Context, *DeleteFavouriteRequest) (*DeleteFavouriteResponse, error)
	DeleteFavouritesByUserID(context.Context, *DeleteFavouritedByUserIDRequest) (*DeleteFavouritedByUserIDResponse, error)
	mustEmbedUnimplementedMemoryServiceServer()
}

// UnimplementedMemoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemoryServiceServer struct{}

func (UnimplementedMemoryServiceServer) CreateMemory(context.Context, *CreateMemoryRequest) (*CreateMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMemory not implemented")
}
func (UnimplementedMemoryServiceServer) DeleteMemory(context.Context, *DeleteMemoryRequest) (*DeleteMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMemory not implemented")
}
func (UnimplementedMemoryServiceServer) DeleteMemoriesByGroup(context.Context, *DeleteMemoriesByGroupRequest) (*DeleteMemoriesByGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMemoriesByGroup not implemented")
}
func (UnimplementedMemoryServiceServer) ListMemoriesByGroup(context.Context, *ListMemoriesByGroupRequest) (*ListMemoriesByGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMemoriesByGroup not implemented")
}
func (UnimplementedMemoryServiceServer) ListMemoriesByGroupWithFilters(context.Context, *ListMemoriesByGroupWithFiltersRequest) (*ListMemoriesByGroupWithFiltersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMemoriesByGroupWithFilters not implemented")
}
func (UnimplementedMemoryServiceServer) CreateMemoryTag(context.Context, *CreateMemoryTagRequest) (*CreateMemoryTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMemoryTag not implemented")
}
func (UnimplementedMemoryServiceServer) DeleteMemoryTag(context.Context, *DeleteMemoryTagRequest) (*DeleteMemoryTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMemoryTag not implemented")
}
func (UnimplementedMemoryServiceServer) ListMemoryTagsByMemoryID(context.Context, *ListMemoryTagsByMemoryIDRequest) (*ListMemoryTagsByMemoryIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMemoryTagsByMemoryID not implemented")
}
func (UnimplementedMemoryServiceServer) CreateFavourite(context.Context, *CreateFavouriteRequest) (*CreateFavouriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFavourite not implemented")
}
func (UnimplementedMemoryServiceServer) DeleteFavourite(context.Context, *DeleteFavouriteRequest) (*DeleteFavouriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFavourite not implemented")
}
func (UnimplementedMemoryServiceServer) DeleteFavouritesByUserID(context.Context, *DeleteFavouritedByUserIDRequest) (*DeleteFavouritedByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFavouritesByUserID not implemented")
}
func (UnimplementedMemoryServiceServer) mustEmbedUnimplementedMemoryServiceServer() {}
func (UnimplementedMemoryServiceServer) testEmbeddedByValue()                       {}

// UnsafeMemoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoryServiceServer will
// result in compilation errors.
type UnsafeMemoryServiceServer interface {
	mustEmbedUnimplementedMemoryServiceServer()
}

func RegisterMemoryServiceServer(s grpc.ServiceRegistrar, srv MemoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedMemoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemoryService_ServiceDesc, srv)
}

func _MemoryService_CreateMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).CreateMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_CreateMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).CreateMemory(ctx, req.(*CreateMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_DeleteMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).DeleteMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_DeleteMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).DeleteMemory(ctx, req.(*DeleteMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_DeleteMemoriesByGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMemoriesByGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).DeleteMemoriesByGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_DeleteMemoriesByGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).DeleteMemoriesByGroup(ctx, req.(*DeleteMemoriesByGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_ListMemoriesByGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMemoriesByGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).ListMemoriesByGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_ListMemoriesByGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).ListMemoriesByGroup(ctx, req.(*ListMemoriesByGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_ListMemoriesByGroupWithFilters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMemoriesByGroupWithFiltersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).ListMemoriesByGroupWithFilters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_ListMemoriesByGroupWithFilters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).ListMemoriesByGroupWithFilters(ctx, req.(*ListMemoriesByGroupWithFiltersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_CreateMemoryTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMemoryTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).CreateMemoryTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_CreateMemoryTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).CreateMemoryTag(ctx, req.(*CreateMemoryTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_DeleteMemoryTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMemoryTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).DeleteMemoryTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_DeleteMemoryTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).DeleteMemoryTag(ctx, req.(*DeleteMemoryTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_ListMemoryTagsByMemoryID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMemoryTagsByMemoryIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).ListMemoryTagsByMemoryID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_ListMemoryTagsByMemoryID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).ListMemoryTagsByMemoryID(ctx, req.(*ListMemoryTagsByMemoryIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_CreateFavourite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFavouriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).CreateFavourite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_CreateFavourite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).CreateFavourite(ctx, req.(*CreateFavouriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_DeleteFavourite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFavouriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).DeleteFavourite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_DeleteFavourite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).DeleteFavourite(ctx, req.(*DeleteFavouriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_DeleteFavouritesByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFavouritedByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).DeleteFavouritesByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_DeleteFavouritesByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).DeleteFavouritesByUserID(ctx, req.(*DeleteFavouritedByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemoryService_ServiceDesc is the grpc.ServiceDesc for MemoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memory.MemoryService",
	HandlerType: (*MemoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMemory",
			Handler:    _MemoryService_CreateMemory_Handler,
		},
		{
			MethodName: "DeleteMemory",
			Handler:    _MemoryService_DeleteMemory_Handler,
		},
		{
			MethodName: "DeleteMemoriesByGroup",
			Handler:    _MemoryService_DeleteMemoriesByGroup_Handler,
		},
		{
			MethodName: "ListMemoriesByGroup",
			Handler:    _MemoryService_ListMemoriesByGroup_Handler,
		},
		{
			MethodName: "ListMemoriesByGroupWithFilters",
			Handler:    _MemoryService_ListMemoriesByGroupWithFilters_Handler,
		},
		{
			MethodName: "CreateMemoryTag",
			Handler:    _MemoryService_CreateMemoryTag_Handler,
		},
		{
			MethodName: "DeleteMemoryTag",
			Handler:    _MemoryService_DeleteMemoryTag_Handler,
		},
		{
			MethodName: "ListMemoryTagsByMemoryID",
			Handler:    _MemoryService_ListMemoryTagsByMemoryID_Handler,
		},
		{
			MethodName: "CreateFavourite",
			Handler:    _MemoryService_CreateFavourite_Handler,
		},
		{
			MethodName: "DeleteFavourite",
			Handler:    _MemoryService_DeleteFavourite_Handler,
		},
		{
			MethodName: "DeleteFavouritesByUserID",
			Handler:    _MemoryService_DeleteFavouritesByUserID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/memory.proto",
}
