syntax = "proto3";

package auth;

option go_package = "Rewind-2.0/Backend/auth_service/proto";

service AuthService {
  rpc StartRegistration(StartRegistrationRequest) returns (StartRegistrationResponse) {}
  rpc VerifyEmailCode(VerifyEmailCodeRequest) returns (VerifyEmailCodeResponse) {}
  rpc SetPasswordAndUsername(SetPasswordAndUsernameRequest) returns (SetPasswordAndUsernameResponse) {}
  rpc Login(LoginRequest) returns (LoginResponse) {}
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse) {}
}

message StartRegistrationRequest {
  string email = 1;
}

message StartRegistrationResponse {
  string registration_id = 1; // Unique ID to track the registration process
  bool success = 2;
}

message VerifyEmailCodeRequest {
  string registration_id = 1;
  string verification_code = 2;
}

message VerifyEmailCodeResponse {
  bool success = 1;
}

message SetPasswordAndUsernameRequest {
  string registration_id = 1;
  string password = 2;
  string username = 3;
}

message SetPasswordAndUsernameResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message LoginRequest {
  string identifier = 1; // Может быть email или username
  string password = 2;
}

message LoginResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message RefreshTokenRequest {
  string refresh_token = 1;
}

message RefreshTokenResponse {
  string access_token = 1;
}