syntax = "proto3";

package auth;

option go_package = "Rewind-2.0/Backend/auth_service/proto";

service AuthService {
  rpc StartRegistration(StartRegistrationRequest) returns (StartRegistrationResponse) {}
  rpc VerifyEmailCode(VerifyEmailCodeRequest) returns (VerifyEmailCodeResponse) {}
  rpc SetPasswordAndUsername(SetPasswordAndUsernameRequest) returns (SetPasswordAndUsernameResponse) {}
  rpc Login(LoginRequest) returns (LoginResponse) {}
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse) {}
  rpc ForgotPassword(ForgotPasswordRequest) returns (ForgotPasswordResponse) {}
  rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse) {}
  rpc Logout(LogoutRequest) returns (LogoutResponse) {}
  rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse) {}
  rpc GetUsersByIDs(GetUsersByIDsRequest) returns (GetUsersByIDsResponse) {}
  rpc GetUserByID(GetUserByIDRequest) returns (GetUserByIDResponse) {}
  rpc UpdateUsername(UpdateUsernameRequest) returns (UpdateUsernameResponse) {}
  rpc CheckPassword(CheckPasswordRequest) returns (CheckPasswordResponse) {}
  rpc UpdateEmail(UpdateEmailRequest) returns (UpdateEmailResponse) {}
  rpc VerifyNewEmailCode(VerifyNewEmailCodeRequest) returns (VerifyNewEmailCodeResponse) {}
  rpc UpdateAvatar(UpdateAvatarRequest) returns (UpdateAvatarResponse) {}
  rpc StartPasswordReset(StartPasswordResetRequest) returns (StartPasswordResetResponse) {}
  rpc VerifyPasswordResetCode(VerifyPasswordResetCodeRequest) returns (VerifyPasswordResetCodeResponse) {}
  rpc SetNewPassword(SetNewPasswordRequest) returns (SetNewPasswordResponse) {}
  rpc DeleteAvatar(DeleteAvatarRequest) returns (DeleteAvatarResponse) {}
  rpc UserAddedMemory(UserAddedMemoryRequest) returns (UserAddedMemoryResponse) {}
  rpc UserInvitedMember(UserInvitedMemberRequest) returns (UserInvitedMemberResponse) {}
}

message User {
  uint64 id = 1;
  string username = 2;
  string email = 3;
  string image = 4;
  uint64 memories_added_count = 5;
  uint64 invited_members_count = 6;
  uint64 memories_viewed_count = 7;
}

message StartRegistrationRequest {
  string email = 1;
}

message StartRegistrationResponse {
  string registration_id = 1; // Unique ID to track the registration process
  bool success = 2;
}

message VerifyEmailCodeRequest {
  string registration_id = 1;
  string verification_code = 2;
}

message VerifyEmailCodeResponse {
  bool success = 1;
}

message SetPasswordAndUsernameRequest {
  string registration_id = 1;
  string password = 2;
  string username = 3;
}

message SetPasswordAndUsernameResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message RefreshTokenRequest {
  string refresh_token = 1;
}

message RefreshTokenResponse {
  string access_token = 1;
}

message ForgotPasswordRequest {
  string email = 1;
}

message ForgotPasswordResponse {
  bool success = 1;
}

message ResetPasswordRequest {
  string token = 1;
  string new_password = 2;
}

message ResetPasswordResponse {
  bool success = 1;
}

message LogoutRequest {
  string refresh_token = 1;
}

message LogoutResponse {
  bool success = 1;
}

message DeleteUserRequest {
  uint64 user_id = 1;
}

message DeleteUserResponse {
  bool success = 1;
}

message GetUsersByIDsRequest {
  repeated uint64 user_ids = 1;
}

message GetUsersByIDsResponse {
  repeated User users = 1;
}

message GetUserByIDRequest {
  uint64 user_id = 1;
}

message GetUserByIDResponse {
  User user = 1;
}

message UpdateUsernameRequest {
  uint64 user_id = 1;
  string new_username = 2;
}

message UpdateUsernameResponse {
  bool success = 1;
}

message CheckPasswordRequest {
  uint64 user_id = 1;
  string password = 2;
}

message CheckPasswordResponse {
  bool success = 1;
}

message UpdateEmailRequest {
  uint64 user_id = 1;
  string new_email = 2;
}

message UpdateEmailResponse {
  bool success = 1;
}

message VerifyNewEmailCodeRequest {
  uint64 user_id = 1;
  string verification_code = 2;
}

message VerifyNewEmailCodeResponse {
  bool success = 1;
}

message UpdateAvatarRequest {
  uint64 user_id = 1;
  bytes image = 2;
}

message UpdateAvatarResponse {
  bool success = 1;
}

message StartPasswordResetRequest {
  uint64 user_id = 1;
}

message StartPasswordResetResponse {
  bool success = 1;
}

message VerifyPasswordResetCodeRequest {
  uint64 user_id = 1;
  string verification_code = 2;
}

message VerifyPasswordResetCodeResponse {
  bool success = 1;
}

message SetNewPasswordRequest {
  uint64 user_id = 1;
  string new_password = 2;
}

message SetNewPasswordResponse {
  bool success = 1;
}

message DeleteAvatarRequest {
  uint64 user_id = 1;
}

message DeleteAvatarResponse {
  bool success = 1;
}

message UserAddedMemoryRequest {
  uint64 user_id = 1;
}

message UserAddedMemoryResponse {
  bool success = 1;
}

message UserInvitedMemberRequest {
  uint64 user_id = 1;
}

message UserInvitedMemberResponse {
  bool success = 1;
}